-- `scenarios` rows generated by tools/scenario_content.py
-- sources: retail captures (builds 69497, 69587, 69814), client DB2 (Scenario, Map,
-- MapDifficulty, LFGDungeons). Provenance per row in the trailing comment. (map, difficulty)
-- keys that already have a row are never emitted. scenario_A = scenario_H; dungeonID 0 like every
-- existing row.

-- (a) captured: the scenario a retail capture ran on this map and difficulty
DELETE FROM `scenarios` WHERE (`map`,`difficulty`) IN ((595,236),(1762,2),(2291,236),(2520,205),(2521,205),(2699,12),(2805,1),(2811,1),(2813,1),(2825,205),(2859,1),(2874,1),(2915,1),(2923,1),(2993,1));
INSERT INTO `scenarios` (`map`,`difficulty`,`dungeonID`,`scenario_A`,`scenario_H`) VALUES
(595,236,0,3034,3034), -- The Culling of Stratholme (Lorewalking): The Culling of Stratholme, captured in a retail capture (build 69497)
(1762,2,0,1565,1565), -- Kings' Rest (Heroic): Kings' Rest, captured in a retail capture (build 69587)
(2291,236,0,3210,3210), -- De Other Side (Lorewalking): De Other Side, captured in a retail capture (build 69497)
(2520,205,0,2074,2074), -- Brackenhide Hollow (Follower): Brackenhide Hollow, captured in a retail capture (build 69814)
(2521,205,0,2083,2083), -- Ruby Life Pools (Follower): Ruby Life Pools, captured in a retail capture (build 69814)
(2699,12,0,2352,2352), -- New Candle, New Hope (Normal Scenario): New Candle, New Hope, captured in a retail capture (build 69814)
(2805,1,0,2638,2638), -- Windrunner Spire (Normal): Windrunner Spire, captured in a retail capture (build 69587)
(2811,1,0,2651,2651), -- Magisters' Terrace (Normal): Magisters' Terrace, captured in a retail capture (build 69587)
(2813,1,0,2926,2926), -- Murder Row (Normal): Murder Row, captured in a retail capture (build 69587)
(2825,205,0,3118,3118), -- Den of Nalorakk (Follower): Den of Nalorakk, captured in a retail capture (build 69497)
(2859,1,0,2961,2961), -- The Blinding Vale (Normal): The Blinding Vale, captured in a retail capture (build 69587)
(2874,1,0,3127,3127), -- Maisara Caverns (Normal): Maisara Caverns, captured in a retail capture (build 69587)
(2915,1,0,3132,3132), -- Nexus-Point Xenas (Normal): Nexus-Point Xenas, captured in a retail capture (build 69587)
(2923,1,0,3197,3197), -- Voidscar Arena (Normal): Voidscar Arena, captured in a retail capture (build 69587)
(2993,1,0,3312,3312); -- Altar of Fangs (Normal): Altar of Fangs, captured in a retail capture (build 69587)

-- (b) LFGDungeons.db2: MapID + DifficultyID + ScenarioID
DELETE FROM `scenarios` WHERE (`map`,`difficulty`) IN ((1014,12),(1157,12),(1200,12),(1431,20),(1461,12),(1478,12),(1503,12),(1511,12),(1523,12),(1528,12),(1529,12),(1533,11),(1536,12),(1545,12),(1553,12),(1580,12),(1599,12),(1607,12),(1611,12),(1612,12),(1616,12),(1617,12),(1620,12),(1622,12),(1623,12),(1624,12),(1625,12),(1626,12),(1630,12),(1632,12),(1646,12),(1666,12),(1673,12),(1683,12),(1684,12),(1687,12),(1688,12),(1693,12),(1694,12),(1695,12),(1698,12),(1702,12),(1703,12),(1704,12),(1705,12),(1706,12),(1707,12),(1708,12),(1710,12),(1714,12),(1719,12),(1723,12),(1729,12),(1730,12),(1731,12),(1732,12),(1733,12),(1734,12),(1737,12),(1744,30),(1756,12),(1774,12),(1812,12),(1917,12),(1944,12),(1955,12),(2115,12),(2125,12),(2134,12),(2161,12),(2170,12),(2174,12),(2179,12),(2180,12),(2208,12),(2211,12),(2212,152),(2213,152),(2223,12),(2247,12),(2258,12),(2266,12),(2278,12),(2282,12),(2299,12),(2303,12),(2305,12),(2308,12),(2354,12),(2371,12),(2464,12),(2556,12),(2582,12),(2583,12),(2586,12),(2587,12),(2590,12),(2595,12),(2597,12),(2625,12),(2634,12),(2635,12),(2639,12),(2644,12),(2653,12),(2654,12),(2692,12),(2710,12),(2713,12),(2716,12),(2827,152),(2828,152),(2907,12),(3074,12));
INSERT INTO `scenarios` (`map`,`difficulty`,`dungeonID`,`scenario_A`,`scenario_H`) VALUES
(1014,12,0,943,943), -- Peak of Serenity (Normal Scenario): Serenity's End, LFGDungeons.db2 [1060, 3011]
(1157,12,0,269,269), -- Halfhill Scenario (Normal Scenario): Finding the Secret Ingredient, LFGDungeons.db2 [745, 2624]
(1200,12,0,323,323), -- Bonetown Scenario (Normal Scenario): Bonetown Scenario, LFGDungeons.db2 [770]
(1431,20,0,736,736), -- The Coliseum (20): Fight, Kill, Salute: Last Gladiator Standing, LFGDungeons.db2 [888]
(1461,12,0,795,795), -- Azsuna Scenario (Normal Scenario): Tides of Glory, LFGDungeons.db2 [932]
(1478,12,0,874,874), -- The Temple of Elune (Normal Scenario): Temple of Elune, LFGDungeons.db2 [990, 3027]
(1503,12,0,950,950), -- Deepholm (Normal Scenario): Cleansing of the Deep, LFGDungeons.db2 [1065, 2914]
(1511,12,0,973,973), -- Tideskorn Harbor (Normal Scenario): The Spear in the Shadow, LFGDungeons.db2 [1178, 1384, 2930, 2948]
(1523,12,0,975,975), -- Defense of the Fel Hammer Scenario (Normal Scenario): Defense of the Fel Hammer, LFGDungeons.db2 [1094, 1422, 2979]
(1528,12,0,983,983), -- Skywall (Normal Scenario): The Thundering Heavens, LFGDungeons.db2 [1145, 2924]
(1529,12,0,989,989), -- Karazhan (Normal Scenario): Return to Karazhan, LFGDungeons.db2 [1347, 2960]
(1533,11,0,2635,2635), -- Karazhan Catacombs (11): Ratts' Revenge, LFGDungeons.db2 [2731]
(1536,12,0,990,990), -- Ursocs Lair (Normal Scenario): Ursoc's Lair, LFGDungeons.db2 [1170, 2936]
(1545,12,0,1012,1012), -- Azsuna (Normal Scenario): The Dread Admiral, LFGDungeons.db2 [1167, 2917]
(1553,12,0,1025,1025), -- Gloaming Reef (Normal Scenario): Tides of Glory, LFGDungeons.db2 [1164]
(1580,12,0,1274,1274), -- The Maelstrom (Normal Scenario): The Sunken Vault, LFGDungeons.db2 [1447]
(1599,12,0,1061,1061), -- Nordrassil (Normal Scenario): Cleansing the Mother Tree, LFGDungeons.db2 [1227, 2935]
(1607,12,0,1078,1078), -- Artifact - Acquisition - Subtlety (Normal Scenario): The Fangs of the Devourer, LFGDungeons.db2 [1240, 2916]
(1611,12,0,1157,1157), -- Death Knight Campaign - Light's Hope Chapel (Normal Scenario): The Fourth Horseman, LFGDungeons.db2 [1320, 3032]
(1612,12,0,1108,1108), -- The Ruins of Falanaar (Normal Scenario): The Fangs of Ashamane, LFGDungeons.db2 [1279, 2937]
(1616,12,0,1221,1221), -- Faronaar (Normal Scenario): An Impossible Foe, LFGDungeons.db2 [1417]
(1617,12,0,1134,1134), -- Death Knight Campaign - Undercity (Normal Scenario): Rescue Koltira, LFGDungeons.db2 [1295, 3031]
(1620,12,0,1123,1123), -- Artifact - Stormwind (Normal Scenario): The Unseen Blade, LFGDungeons.db2 [1281, 2918]
(1622,12,0,1410,1410), -- Telogrus Rift Scenario (Normal Scenario): Telogrus Rift, LFGDungeons.db2 [1616]
(1623,12,0,1135,1135), -- Mage Campaign - The Oculus (Normal Scenario): The Oculus, LFGDungeons.db2 [1296, 2954]
(1624,12,0,1138,1138), -- Battle of Exodar (Normal Scenario): Battle for the Exodar, LFGDungeons.db2 [1299, 3065]
(1625,12,0,1137,1137), -- Trial of the Serpent (Normal Scenario): The Serpent and the Demon, LFGDungeons.db2 [1298, 2926]
(1626,12,0,1150,1150), -- The Collapse - Suramar Scenario (Normal Scenario): The Collapse, LFGDungeons.db2 [1306, 2953]
(1630,12,0,1155,1155), -- Tol Barad (Normal Scenario): An Eye for a Scepter, LFGDungeons.db2 [1312, 2908]
(1632,12,0,1159,1159), -- The Arcway - Suramar Scenario (Normal Scenario): All In, LFGDungeons.db2 [1321, 2965]
(1646,12,0,1179,1179), -- Black Rook Hold [Scenario] (Normal Scenario): Ravencrest's Legacy, LFGDungeons.db2 [1354]
(1666,12,0,1280,1280), -- The Assault on Broken Shore (Normal Scenario): The Assault on Broken Shore, LFGDungeons.db2 [1470, 2967]
(1673,12,0,1204,1204), -- The Eye of Eternity - Scenario (Normal Scenario): The Archmage's Reckoning, LFGDungeons.db2 [1406]
(1683,12,0,1220,1220), -- Artifact - Gnomeregan (Normal Scenario): Imminent Launch, LFGDungeons.db2 [1416]
(1684,12,0,1273,1273), -- Dread Scar Rift - Warlock Scenario Platform (Normal Scenario): Thwarting the Twins, LFGDungeons.db2 [1452]
(1687,12,0,1235,1235), -- Wailing Caverns (Normal Scenario): Wailing Critters, LFGDungeons.db2 [1430]
(1688,12,0,1293,1293), -- Deadmines (Normal Scenario): The Deadmines, LFGDungeons.db2 [1482]
(1693,12,0,1236,1236), -- Stormstout Brewery - Monk Scenario (Normal Scenario): Panic At The Brewery, LFGDungeons.db2 [1431, 2980]
(1694,12,0,1703,1703), -- Gnomeregan (Normal Scenario): Gnomeregan, LFGDungeons.db2 [1491]
(1695,12,0,1244,1244), -- Battleship: Ruin (Normal Scenario): Battleship: Ruin, LFGDungeons.db2 [1436]
(1698,12,0,1259,1259), -- Artifact - Acquisition - Tank (Normal Scenario): Kruul's Intentions, LFGDungeons.db2 [1440]
(1702,12,0,1266,1266), -- Artifact - Highmountain - Dual Boss (Normal Scenario): Feltotem's Fall, LFGDungeons.db2 [1445]
(1703,12,0,1265,1265), -- Halls of Valor - Scenario (Normal Scenario): The God-Queen's Fury, LFGDungeons.db2 [1446]
(1704,12,0,1271,1271), -- Legion Ship - Horizontal - Valsharah (Normal Scenario): Turn Back the Tides: Val'sharah, LFGDungeons.db2 [1459, 3047]
(1705,12,0,1290,1290), -- Legion Ship - Horizontal - Azsuna (Normal Scenario): Turn Back the Tides: Azsuna, LFGDungeons.db2 [1480, 3045]
(1706,12,0,1299,1299), -- Legion Ship - Vertical - HighMountain (Normal Scenario): Turn Back the Tides: Highmountain, LFGDungeons.db2 [1490, 3044]
(1707,12,0,1282,1282), -- Legion Ship - Vertical - Stormheim (Normal Scenario): Turn Back the Tides: Stormheim, LFGDungeons.db2 [1472, 3046]
(1708,12,0,1275,1275), -- Stratholme - Paladin Class Mount (Normal Scenario): Stirring in the Shadows, LFGDungeons.db2 [1458, 2974]
(1710,12,0,1281,1281), -- Black Rook Hold - Artifact Challenge (Normal Scenario): End of the Risen Threat, LFGDungeons.db2 [1471]
(1714,12,0,1283,1283), -- Halls Of Valor - Warrior Class Mount (Normal Scenario): Tournament of Valor, LFGDungeons.db2 [1473, 2978]
(1719,12,0,1298,1298), -- Dread Scar Rift - Warlock Mount Scenario (Normal Scenario): Calling the Wrathsteed, LFGDungeons.db2 [1489, 2977]
(1723,12,0,1292,1292), -- Coldridge Valley (Normal Scenario): The Coldridge Cataclysm, LFGDungeons.db2 [1481]
(1729,12,0,1230,1230), -- The Eye of Eternity - Mage Class Mount (Shorter Version) (Normal Scenario): Dispersion of the Discs, LFGDungeons.db2 [1423, 2973]
(1730,12,0,1306,1306), -- Shrine of Aviana Defense - Scenario (Normal Scenario): Defense of Aviana, LFGDungeons.db2 [1492, 3029]
(1731,12,0,1312,1312), -- Druid Mount Finale - Scenario (Normal Scenario): You Can't Take the Sky from Me, LFGDungeons.db2 [1501, 3028]
(1732,12,0,1303,1303), -- Felwing Ledge - Demon Hunter Class Mount (Normal Scenario): Felwing Ledge, LFGDungeons.db2 [1493, 2971]
(1733,12,0,1304,1304), -- Azeroth's Warning Scenario (Normal Scenario): Azeroth's Warning, LFGDungeons.db2 [1498, 2981]
(1734,12,0,1307,1307), -- Throne of the Four Winds - Shaman Class Mount (Normal Scenario): Gathering of the Storms, LFGDungeons.db2 [1499, 2976]
(1737,12,0,1310,1310), -- Pocket Dimension Akazamzaraks Hat Scenario (Normal Scenario): Akazamzarak's Hat, LFGDungeons.db2 [1500, 2968]
(1744,30,0,1329,1329), -- Trial of Style (30): The Trial of Style, LFGDungeons.db2 [1515]
(1756,12,0,1351,1351), -- The Deaths of Chromie (Normal Scenario): The Deaths of Chromie, LFGDungeons.db2 [1534, 2982]
(1774,12,0,1434,1434), -- Forge of Aeons (Normal Scenario): Forge of Aeons, LFGDungeons.db2 [1643]
(1812,12,0,1423,1423), -- Suramar (Normal Scenario): Suramar, LFGDungeons.db2 [1634]
(1917,12,0,1575,1575), -- Gorgrond - Mag'har Scenario (Normal Scenario): Tyranny of the Light, LFGDungeons.db2 [1771]
(1944,12,0,1551,1551), -- Thros, The Blighted Lands (Normal Scenario): Thros, the Blighted Lands, LFGDungeons.db2 [1753]
(1955,12,0,1573,1573), -- Uncharted Island (Normal Scenario): Uncharted Island, LFGDungeons.db2 [1768]
(2115,12,0,1700,1700), -- 8.1 Darkshore Scenario (Normal Scenario): Tyrande's Ascension, LFGDungeons.db2 [1907]
(2125,12,0,1702,1702), -- Zandalari Treasury (Normal Scenario): The Treasury Heist, LFGDungeons.db2 [1909]
(2134,12,0,1705,1705), -- Tol Dagor Scenario (Normal Scenario): Escape from Tol Dagor, LFGDungeons.db2 [1911]
(2161,12,0,1712,1712), -- Maw Prototype - Torment Chambers (Normal Scenario): Torghast, Tower of the Damned, LFGDungeons.db2 [1955]
(2170,12,0,1711,1711), -- Tauren Heritage Scenario (Normal Scenario): Spirit Hunt, LFGDungeons.db2 [1959]
(2174,12,0,1722,1722), -- Scarlet Halls, Dark Ranger (Normal Scenario): The Misssing Apprentice, LFGDungeons.db2 [1999]
(2179,12,0,1724,1724), -- Stratholme Pet Dungeon (Normal Scenario): Stratholme, LFGDungeons.db2 [1964]
(2180,12,0,1721,1721), -- The Dreamgrove (Hearthstone Tavern) (Normal Scenario): Tradewind & Crow: Dreamgrove Detectives, LFGDungeons.db2 [1962]
(2208,12,0,1729,1729), -- Eastern Kingdoms - Vermillion Redoubt - HoA Scenario (Normal Scenario): In the Shadow of Crimson Wings, LFGDungeons.db2 [1992]
(2211,12,0,1732,1732), -- Gilneas - Worgen Heritage Scenario (Normal Scenario): A Gilnean's Dream, LFGDungeons.db2 [1994]
(2212,152,0,1733,1733), -- Horrific Vision of Orgrimmar (152): Vision of Orgrimmar, LFGDungeons.db2 [1995]
(2213,152,0,1731,1731), -- Horrific Vision of Stormwind (152): Vision of Stormwind, LFGDungeons.db2 [1993]
(2223,12,0,1736,1736), -- The Eye of Eternity - HoA Scenario (Normal Scenario): Essence of Eternity, LFGDungeons.db2 [2001]
(2247,12,0,1757,1757), -- Mogu'shan Scenario (Normal Scenario): The Engine of Nalak'sha, LFGDungeons.db2 [2012]
(2258,12,0,1765,1765), -- Crapopolis - Scenario (Normal Scenario): Crapopolis, LFGDungeons.db2 [2022]
(2266,12,0,1764,1764), -- Blackwing Descent Scenario (Normal Scenario): Blackwing Descent, LFGDungeons.db2 [2021]
(2278,12,0,1767,1767), -- Revendreth Scenario (Normal Scenario): The Master of Lies, LFGDungeons.db2 [2030]
(2282,12,0,1777,1777), -- Blackrock Depths - Pet Dungeon (Normal Scenario): Blackrock Depths, LFGDungeons.db2 [2040]
(2299,12,0,1781,1781), -- Vision of Ysera Scenario (Normal Scenario): End of the Dream, LFGDungeons.db2 [2045]
(2303,12,0,1783,1783), -- Ardenweald Zone Scenario (Normal Scenario): Battle for Tirna Glayn, LFGDungeons.db2 [2049]
(2305,12,0,1790,1790), -- Bastion Scenario (Normal Scenario): The Greater Good, LFGDungeons.db2 [2061]
(2308,12,0,1784,1784), -- Bastion Night Warrior Finale - Ardenweald Covenant Scenario (Normal Scenario): The Path of Totality, LFGDungeons.db2 [2050]
(2354,12,0,1785,1785), -- Ardenweald Covenant Chapter 2 Scenario (Normal Scenario): Recovering Tyrande Whisperwind, LFGDungeons.db2 [2059]
(2371,12,0,1794,1794), -- 9.0 Ardenweald Covenant Finale Drust Scenario (Normal Scenario): Battle for The Grove of Awakening, LFGDungeons.db2 [2068]
(2464,12,0,1931,1931), -- 9.1 Battle of Ardenweald (Normal Scenario): Battle of Ardenweald, LFGDungeons.db2 [2190]
(2556,12,0,2047,2047), -- Emerald Dreamway (Normal Scenario): Emerald Dreamway, LFGDungeons.db2 [2349]
(2582,12,0,2137,2137), -- Alterac Valley (Normal Scenario): The Future of Our People, LFGDungeons.db2 [2387]
(2583,12,0,2136,2136), -- Tyr's Fall Scenario (Normal Scenario): Tyr's Fall, LFGDungeons.db2 [2386]
(2586,12,0,2278,2278), -- 10.1.5 Time Rifts - Murloc (Azmerloth) (Normal Scenario): Timeway: Azmerloth, LFGDungeons.db2 [2408]
(2587,12,0,2285,2285), -- 10.1.5 Time Rifts - Robot (A.Z.E.R.O.T.H.) (Normal Scenario): Timeway: A.Z.E.R.O.T.H., LFGDungeons.db2 [2429]
(2590,12,0,2145,2145), -- The Azure Vault (Normal Scenario): The Last Conflict, LFGDungeons.db2 [2391]
(2595,12,0,2282,2282), -- 10.1.5 Time Rifts - Demon (Azewrath) (Normal Scenario): Timeway: Azewrath, LFGDungeons.db2 [2426]
(2597,12,0,2146,2146), -- 10.1 Zaralek Caverns - Chapter 1 Scenario (Normal Scenario): The Patience of Princes, LFGDungeons.db2 [2392]
(2625,12,0,2154,2154), -- Deathwing's Final Moment (Normal Scenario): Nasz'uro, the Unbound Legacy, LFGDungeons.db2 [2397]
(2634,12,0,2284,2284), -- 10.1.5 Time Rifts - HvA (The Warlands) (Normal Scenario): Timeway: The Warlands, LFGDungeons.db2 [2428]
(2635,12,0,2280,2280), -- 10.1.5 Time Rifts - Titan (Ulderoth) (Normal Scenario): Timeway: Ulderoth, LFGDungeons.db2 [2425]
(2639,12,0,2281,2281), -- 10.1.5 Time Rifts - Scourge (Azmourne) (Normal Scenario): Timeway: Azmourne, LFGDungeons.db2 [2409]
(2644,12,0,2290,2290), -- 10.2.0 - Halls of Valor - Misfit Dragons (Normal Scenario): Storm the Halls of Valor, LFGDungeons.db2 [2423]
(2653,12,0,2286,2286), -- 10.2 Scenario (Normal Scenario): A Hero's Resolve, LFGDungeons.db2 [2433]
(2654,12,0,2296,2296), -- 10.2. Nighthold (Normal Scenario): Retrieving the Disc, LFGDungeons.db2 [2434]
(2692,12,0,2338,2338), -- Hall of Awakening (Normal Scenario): Hall of Awakening, LFGDungeons.db2 [2499]
(2710,12,0,2392,2392), -- Awakening The Machine (Normal Scenario): Awakening The Machine, LFGDungeons.db2 [2532]
(2713,12,0,2388,2388), -- 11.0 - Campaign Finale Scenario (Normal Scenario): Escape The Burrows!, LFGDungeons.db2 [2531]
(2716,12,0,2416,2416), -- 11.0 - Priory Scenario (Normal Scenario): A Light in the Dark, LFGDungeons.db2 [2534]
(2827,152,0,2950,2950), -- Horrific Vision of Stormwind (152): Vision of Stormwind, LFGDungeons.db2 [2758]
(2828,152,0,2951,2951), -- Horrific Vision of Orgrimmar (152): Vision of Orgrimmar, LFGDungeons.db2 [2759]
(2907,12,0,2943,2943), -- 12.0 - Silvermoon City - Campaign Finale Scenario (Normal Scenario): The Battle of the Bridge, LFGDungeons.db2 [2816]
(3074,12,0,3267,3267); -- Daggerspine Point (Normal Scenario): Daggerspine Point, LFGDungeons.db2 [3170]

-- (c) rule R1: per-difficulty dungeon scenario ids from Scenario.db2 names
DELETE FROM `scenarios` WHERE (`map`,`difficulty`) IN ((2451,205),(2515,205),(2516,205),(2519,205),(2526,205),(2527,205),(2648,1),(2648,2),(2648,8),(2648,23),(2648,205),(2649,1),(2649,2),(2649,8),(2649,23),(2649,205),(2651,1),(2651,2),(2651,8),(2651,23),(2651,205),(2652,1),(2652,2),(2652,8),(2652,23),(2652,205),(2660,1),(2660,2),(2660,8),(2660,23),(2660,205),(2661,1),(2661,2),(2661,8),(2661,23),(2661,205),(2662,1),(2662,2),(2662,8),(2662,23),(2662,205),(2773,1),(2773,2),(2773,8),(2773,23),(2773,205),(2805,2),(2805,8),(2805,23),(2805,205),(2811,2),(2811,8),(2811,23),(2811,205),(2813,2),(2813,8),(2813,23),(2813,205),(2825,1),(2825,2),(2825,8),(2825,23),(2830,1),(2830,2),(2830,8),(2830,23),(2830,205),(2859,2),(2859,8),(2859,23),(2859,205),(2874,2),(2874,8),(2874,23),(2874,205),(2915,2),(2915,8),(2915,23),(2915,205),(2923,2),(2923,8),(2923,23),(2923,205),(2993,2),(2993,8),(2993,23),(2993,205));
INSERT INTO `scenarios` (`map`,`difficulty`,`dungeonID`,`scenario_A`,`scenario_H`) VALUES
(2451,205,0,2092,2092), -- Uldaman: Legacy of Tyr (Follower): Uldaman: Legacy of Tyr, R1: name group 'Uldaman: Legacy of Tyr' is unambiguous (Type-3 [2092, 2093, 2094], Type-1 [2188]) (follower runs the normal id)
(2515,205,0,2089,2089), -- The Azure Vault (Follower): The Azure Vault, R1: name group 'The Azure Vault' is unambiguous (Type-3 [2089, 2090, 2091], Type-1 [2133]) (follower runs the normal id)
(2516,205,0,2059,2059), -- The Nokhud Offensive (Follower): The Nokhud Offensive, R1: name group 'The Nokhud Offensive' is unambiguous (Type-3 [2059, 2061, 2073], Type-1 [2132]) (follower runs the normal id)
(2519,205,0,2080,2080), -- Neltharus (Follower): Neltharus, R1: name group 'Neltharus' is unambiguous (Type-3 [2080, 2081, 2082], Type-1 [2189]) (follower runs the normal id)
(2526,205,0,2086,2086), -- Algeth'ar Academy (Follower): Algeth'ar Academy, R1: name group 'Algeth'ar Academy' is unambiguous (Type-3 [2086, 2087, 2088], Type-1 [2131]) (follower runs the normal id)
(2527,205,0,2077,2077), -- Halls of Infusion (Follower): Halls of Infusion, R1: name group 'Halls of Infusion' is unambiguous (Type-3 [2077, 2078, 2079], Type-1 [2190]) (follower runs the normal id)
(2648,1,0,2368,2368), -- The Rookery (Normal): The Rookery, R1: name group 'The Rookery' is unambiguous (Type-3 [2368, 2369, 2370], Type-1 [2443])
(2648,2,0,2369,2369), -- The Rookery (Heroic): The Rookery, R1: name group 'The Rookery' is unambiguous (Type-3 [2368, 2369, 2370], Type-1 [2443])
(2648,8,0,2443,2443), -- The Rookery (Mythic Keystone): The Rookery, R1: name group 'The Rookery' is unambiguous (Type-3 [2368, 2369, 2370], Type-1 [2443])
(2648,23,0,2370,2370), -- The Rookery (Mythic): The Rookery, R1: name group 'The Rookery' is unambiguous (Type-3 [2368, 2369, 2370], Type-1 [2443])
(2648,205,0,2368,2368), -- The Rookery (Follower): The Rookery, R1: name group 'The Rookery' is unambiguous (Type-3 [2368, 2369, 2370], Type-1 [2443]) (follower runs the normal id)
(2649,1,0,2552,2552), -- Priory of the Sacred Flame (Normal): Priory of the Sacred Flame, R1: name group 'Priory of the Sacred Flame' is unambiguous (Type-3 [2552, 2553, 2554], Type-1 [2439])
(2649,2,0,2553,2553), -- Priory of the Sacred Flame (Heroic): Priory of the Sacred Flame, R1: name group 'Priory of the Sacred Flame' is unambiguous (Type-3 [2552, 2553, 2554], Type-1 [2439])
(2649,8,0,2439,2439), -- Priory of the Sacred Flame (Mythic Keystone): Priory of the Sacred Flame, R1: name group 'Priory of the Sacred Flame' is unambiguous (Type-3 [2552, 2553, 2554], Type-1 [2439])
(2649,23,0,2554,2554), -- Priory of the Sacred Flame (Mythic): Priory of the Sacred Flame, R1: name group 'Priory of the Sacred Flame' is unambiguous (Type-3 [2552, 2553, 2554], Type-1 [2439])
(2649,205,0,2552,2552), -- Priory of the Sacred Flame (Follower): Priory of the Sacred Flame, R1: name group 'Priory of the Sacred Flame' is unambiguous (Type-3 [2552, 2553, 2554], Type-1 [2439]) (follower runs the normal id)
(2651,1,0,2327,2327), -- Darkflame Cleft (Normal): Darkflame Cleft, R1: name group 'Darkflame Cleft' is unambiguous (Type-3 [2327, 2328, 2329], Type-1 [2447])
(2651,2,0,2328,2328), -- Darkflame Cleft (Heroic): Darkflame Cleft, R1: name group 'Darkflame Cleft' is unambiguous (Type-3 [2327, 2328, 2329], Type-1 [2447])
(2651,8,0,2447,2447), -- Darkflame Cleft (Mythic Keystone): Darkflame Cleft, R1: name group 'Darkflame Cleft' is unambiguous (Type-3 [2327, 2328, 2329], Type-1 [2447])
(2651,23,0,2329,2329), -- Darkflame Cleft (Mythic): Darkflame Cleft, R1: name group 'Darkflame Cleft' is unambiguous (Type-3 [2327, 2328, 2329], Type-1 [2447])
(2651,205,0,2327,2327), -- Darkflame Cleft (Follower): Darkflame Cleft, R1: name group 'Darkflame Cleft' is unambiguous (Type-3 [2327, 2328, 2329], Type-1 [2447]) (follower runs the normal id)
(2652,1,0,2364,2364), -- The Stonevault (Normal): The Stonevault, R1: name group 'The Stonevault' is unambiguous (Type-3 [2364, 2366, 2367], Type-1 [2444])
(2652,2,0,2366,2366), -- The Stonevault (Heroic): The Stonevault, R1: name group 'The Stonevault' is unambiguous (Type-3 [2364, 2366, 2367], Type-1 [2444])
(2652,8,0,2444,2444), -- The Stonevault (Mythic Keystone): The Stonevault, R1: name group 'The Stonevault' is unambiguous (Type-3 [2364, 2366, 2367], Type-1 [2444])
(2652,23,0,2367,2367), -- The Stonevault (Mythic): The Stonevault, R1: name group 'The Stonevault' is unambiguous (Type-3 [2364, 2366, 2367], Type-1 [2444])
(2652,205,0,2364,2364), -- The Stonevault (Follower): The Stonevault, R1: name group 'The Stonevault' is unambiguous (Type-3 [2364, 2366, 2367], Type-1 [2444]) (follower runs the normal id)
(2660,1,0,2394,2394), -- Ara-Kara, City of Echoes (Normal): Ara-Kara, City of Echoes, R1: name group 'Ara-Kara, City of Echoes' is unambiguous (Type-3 [2394, 2395, 2396], Type-1 [2446])
(2660,2,0,2395,2395), -- Ara-Kara, City of Echoes (Heroic): Ara-Kara, City of Echoes, R1: name group 'Ara-Kara, City of Echoes' is unambiguous (Type-3 [2394, 2395, 2396], Type-1 [2446])
(2660,8,0,2446,2446), -- Ara-Kara, City of Echoes (Mythic Keystone): Ara-Kara, City of Echoes, R1: name group 'Ara-Kara, City of Echoes' is unambiguous (Type-3 [2394, 2395, 2396], Type-1 [2446])
(2660,23,0,2396,2396), -- Ara-Kara, City of Echoes (Mythic): Ara-Kara, City of Echoes, R1: name group 'Ara-Kara, City of Echoes' is unambiguous (Type-3 [2394, 2395, 2396], Type-1 [2446])
(2660,205,0,2394,2394), -- Ara-Kara, City of Echoes (Follower): Ara-Kara, City of Echoes, R1: name group 'Ara-Kara, City of Echoes' is unambiguous (Type-3 [2394, 2395, 2396], Type-1 [2446]) (follower runs the normal id)
(2661,1,0,2406,2406), -- Cinderbrew Meadery (Normal): Cinderbrew Meadery, R1: name group 'Cinderbrew Meadery' is unambiguous (Type-3 [2406, 2407, 2408], Type-1 [2449])
(2661,2,0,2407,2407), -- Cinderbrew Meadery (Heroic): Cinderbrew Meadery, R1: name group 'Cinderbrew Meadery' is unambiguous (Type-3 [2406, 2407, 2408], Type-1 [2449])
(2661,8,0,2449,2449), -- Cinderbrew Meadery (Mythic Keystone): Cinderbrew Meadery, R1: name group 'Cinderbrew Meadery' is unambiguous (Type-3 [2406, 2407, 2408], Type-1 [2449])
(2661,23,0,2408,2408), -- Cinderbrew Meadery (Mythic): Cinderbrew Meadery, R1: name group 'Cinderbrew Meadery' is unambiguous (Type-3 [2406, 2407, 2408], Type-1 [2449])
(2661,205,0,2406,2406), -- Cinderbrew Meadery (Follower): Cinderbrew Meadery, R1: name group 'Cinderbrew Meadery' is unambiguous (Type-3 [2406, 2407, 2408], Type-1 [2449]) (follower runs the normal id)
(2662,1,0,2381,2381), -- The Dawnbreaker (Normal): The Dawnbreaker, R1: name group 'The Dawnbreaker' is unambiguous (Type-3 [2381, 2382, 2383], Type-1 [2448])
(2662,2,0,2382,2382), -- The Dawnbreaker (Heroic): The Dawnbreaker, R1: name group 'The Dawnbreaker' is unambiguous (Type-3 [2381, 2382, 2383], Type-1 [2448])
(2662,8,0,2448,2448), -- The Dawnbreaker (Mythic Keystone): The Dawnbreaker, R1: name group 'The Dawnbreaker' is unambiguous (Type-3 [2381, 2382, 2383], Type-1 [2448])
(2662,23,0,2383,2383), -- The Dawnbreaker (Mythic): The Dawnbreaker, R1: name group 'The Dawnbreaker' is unambiguous (Type-3 [2381, 2382, 2383], Type-1 [2448])
(2662,205,0,2381,2381), -- The Dawnbreaker (Follower): The Dawnbreaker, R1: name group 'The Dawnbreaker' is unambiguous (Type-3 [2381, 2382, 2383], Type-1 [2448]) (follower runs the normal id)
(2773,1,0,2642,2642), -- Operation: Floodgate (Normal): Operation: Floodgate, R1: name group 'Operation: Floodgate' is unambiguous (Type-3 [2642, 2643, 2644], Type-1 [2680])
(2773,2,0,2643,2643), -- Operation: Floodgate (Heroic): Operation: Floodgate, R1: name group 'Operation: Floodgate' is unambiguous (Type-3 [2642, 2643, 2644], Type-1 [2680])
(2773,8,0,2680,2680), -- Operation: Floodgate (Mythic Keystone): Operation: Floodgate, R1: name group 'Operation: Floodgate' is unambiguous (Type-3 [2642, 2643, 2644], Type-1 [2680])
(2773,23,0,2644,2644), -- Operation: Floodgate (Mythic): Operation: Floodgate, R1: name group 'Operation: Floodgate' is unambiguous (Type-3 [2642, 2643, 2644], Type-1 [2680])
(2773,205,0,2642,2642), -- Operation: Floodgate (Follower): Operation: Floodgate, R1: name group 'Operation: Floodgate' is unambiguous (Type-3 [2642, 2643, 2644], Type-1 [2680]) (follower runs the normal id)
(2805,2,0,2640,2640), -- Windrunner Spire (Heroic): Windrunner Spire, R1: name group 'Windrunner Spire' is unambiguous (Type-3 [2638, 2640, 2641], Type-1 [3189])
(2805,8,0,3189,3189), -- Windrunner Spire (Mythic Keystone): Windrunner Spire, R1: name group 'Windrunner Spire' is unambiguous (Type-3 [2638, 2640, 2641], Type-1 [3189])
(2805,23,0,2641,2641), -- Windrunner Spire (Mythic): Windrunner Spire, R1: name group 'Windrunner Spire' is unambiguous (Type-3 [2638, 2640, 2641], Type-1 [3189])
(2805,205,0,2638,2638), -- Windrunner Spire (Follower): Windrunner Spire, R1: name group 'Windrunner Spire' is unambiguous (Type-3 [2638, 2640, 2641], Type-1 [3189]) (follower runs the normal id)
(2811,2,0,2652,2652), -- Magisters' Terrace (Heroic): Magisters' Terrace, R1 (ambiguous group 'Magisters' Terrace': Type-3 [616, 617, 2585, 2651, 2652, 2653], Type-1 [3190]): captured normal id 2651, the next two consecutive Type-3 ids and the only Type-1 id above it (3190)
(2811,8,0,3190,3190), -- Magisters' Terrace (Mythic Keystone): Magisters' Terrace, R1 (ambiguous group 'Magisters' Terrace': Type-3 [616, 617, 2585, 2651, 2652, 2653], Type-1 [3190]): captured normal id 2651, the next two consecutive Type-3 ids and the only Type-1 id above it (3190)
(2811,23,0,2653,2653), -- Magisters' Terrace (Mythic): Magisters' Terrace, R1 (ambiguous group 'Magisters' Terrace': Type-3 [616, 617, 2585, 2651, 2652, 2653], Type-1 [3190]): captured normal id 2651, the next two consecutive Type-3 ids and the only Type-1 id above it (3190)
(2811,205,0,2651,2651), -- Magisters' Terrace (Follower): Magisters' Terrace, R1 (ambiguous group 'Magisters' Terrace': Type-3 [616, 617, 2585, 2651, 2652, 2653], Type-1 [3190]): captured normal id 2651, the next two consecutive Type-3 ids and the only Type-1 id above it (3190) (follower runs the normal id)
(2813,2,0,2978,2978), -- Murder Row (Heroic): Murder Row, R1: name group 'Murder Row' is unambiguous (Type-3 [2926, 2978, 2979], Type-1 [3372])
(2813,8,0,3372,3372), -- Murder Row (Mythic Keystone): Murder Row, R1: name group 'Murder Row' is unambiguous (Type-3 [2926, 2978, 2979], Type-1 [3372])
(2813,23,0,2979,2979), -- Murder Row (Mythic): Murder Row, R1: name group 'Murder Row' is unambiguous (Type-3 [2926, 2978, 2979], Type-1 [3372])
(2813,205,0,2926,2926), -- Murder Row (Follower): Murder Row, R1: name group 'Murder Row' is unambiguous (Type-3 [2926, 2978, 2979], Type-1 [3372]) (follower runs the normal id)
(2825,1,0,3118,3118), -- Den of Nalorakk (Normal): Den of Nalorakk, R1: name group 'Den of Nalorakk' is unambiguous (Type-3 [3118, 3120, 3121], Type-1 [3371])
(2825,2,0,3120,3120), -- Den of Nalorakk (Heroic): Den of Nalorakk, R1: name group 'Den of Nalorakk' is unambiguous (Type-3 [3118, 3120, 3121], Type-1 [3371])
(2825,8,0,3371,3371), -- Den of Nalorakk (Mythic Keystone): Den of Nalorakk, R1: name group 'Den of Nalorakk' is unambiguous (Type-3 [3118, 3120, 3121], Type-1 [3371])
(2825,23,0,3121,3121), -- Den of Nalorakk (Mythic): Den of Nalorakk, R1: name group 'Den of Nalorakk' is unambiguous (Type-3 [3118, 3120, 3121], Type-1 [3371])
(2830,1,0,2944,2944), -- Eco-Dome Al'dani (Normal): Eco-Dome Al'dani, R1: name group 'Eco-Dome Al'dani' is unambiguous (Type-3 [2944, 2945, 2946], Type-1 [2967])
(2830,2,0,2945,2945), -- Eco-Dome Al'dani (Heroic): Eco-Dome Al'dani, R1: name group 'Eco-Dome Al'dani' is unambiguous (Type-3 [2944, 2945, 2946], Type-1 [2967])
(2830,8,0,2967,2967), -- Eco-Dome Al'dani (Mythic Keystone): Eco-Dome Al'dani, R1: name group 'Eco-Dome Al'dani' is unambiguous (Type-3 [2944, 2945, 2946], Type-1 [2967])
(2830,23,0,2946,2946), -- Eco-Dome Al'dani (Mythic): Eco-Dome Al'dani, R1: name group 'Eco-Dome Al'dani' is unambiguous (Type-3 [2944, 2945, 2946], Type-1 [2967])
(2830,205,0,2944,2944), -- Eco-Dome Al'dani (Follower): Eco-Dome Al'dani, R1: name group 'Eco-Dome Al'dani' is unambiguous (Type-3 [2944, 2945, 2946], Type-1 [2967]) (follower runs the normal id)
(2859,2,0,2962,2962), -- The Blinding Vale (Heroic): The Blinding Vale, R1: name group 'The Blinding Vale' is unambiguous (Type-3 [2961, 2962, 2963], Type-1 [3367])
(2859,8,0,3367,3367), -- The Blinding Vale (Mythic Keystone): The Blinding Vale, R1: name group 'The Blinding Vale' is unambiguous (Type-3 [2961, 2962, 2963], Type-1 [3367])
(2859,23,0,2963,2963), -- The Blinding Vale (Mythic): The Blinding Vale, R1: name group 'The Blinding Vale' is unambiguous (Type-3 [2961, 2962, 2963], Type-1 [3367])
(2859,205,0,2961,2961), -- The Blinding Vale (Follower): The Blinding Vale, R1: name group 'The Blinding Vale' is unambiguous (Type-3 [2961, 2962, 2963], Type-1 [3367]) (follower runs the normal id)
(2874,2,0,3128,3128), -- Maisara Caverns (Heroic): Maisara Caverns, R1: name group 'Maisara Caverns' is unambiguous (Type-3 [3127, 3128, 3129], Type-1 [3192])
(2874,8,0,3192,3192), -- Maisara Caverns (Mythic Keystone): Maisara Caverns, R1: name group 'Maisara Caverns' is unambiguous (Type-3 [3127, 3128, 3129], Type-1 [3192])
(2874,23,0,3129,3129), -- Maisara Caverns (Mythic): Maisara Caverns, R1: name group 'Maisara Caverns' is unambiguous (Type-3 [3127, 3128, 3129], Type-1 [3192])
(2874,205,0,3127,3127), -- Maisara Caverns (Follower): Maisara Caverns, R1: name group 'Maisara Caverns' is unambiguous (Type-3 [3127, 3128, 3129], Type-1 [3192]) (follower runs the normal id)
(2915,2,0,3133,3133), -- Nexus-Point Xenas (Heroic): Nexus-Point Xenas, R1: name group 'Nexus-Point Xenas' is unambiguous (Type-3 [3132, 3133, 3134], Type-1 [3191])
(2915,8,0,3191,3191), -- Nexus-Point Xenas (Mythic Keystone): Nexus-Point Xenas, R1: name group 'Nexus-Point Xenas' is unambiguous (Type-3 [3132, 3133, 3134], Type-1 [3191])
(2915,23,0,3134,3134), -- Nexus-Point Xenas (Mythic): Nexus-Point Xenas, R1: name group 'Nexus-Point Xenas' is unambiguous (Type-3 [3132, 3133, 3134], Type-1 [3191])
(2915,205,0,3132,3132), -- Nexus-Point Xenas (Follower): Nexus-Point Xenas, R1: name group 'Nexus-Point Xenas' is unambiguous (Type-3 [3132, 3133, 3134], Type-1 [3191]) (follower runs the normal id)
(2923,2,0,3198,3198), -- Voidscar Arena (Heroic): Voidscar Arena, R1: name group 'Voidscar Arena' is unambiguous (Type-3 [3197, 3198, 3199], Type-1 [3370])
(2923,8,0,3370,3370), -- Voidscar Arena (Mythic Keystone): Voidscar Arena, R1: name group 'Voidscar Arena' is unambiguous (Type-3 [3197, 3198, 3199], Type-1 [3370])
(2923,23,0,3199,3199), -- Voidscar Arena (Mythic): Voidscar Arena, R1: name group 'Voidscar Arena' is unambiguous (Type-3 [3197, 3198, 3199], Type-1 [3370])
(2923,205,0,3197,3197), -- Voidscar Arena (Follower): Voidscar Arena, R1: name group 'Voidscar Arena' is unambiguous (Type-3 [3197, 3198, 3199], Type-1 [3370]) (follower runs the normal id)
(2993,2,0,3313,3313), -- Altar of Fangs (Heroic): Altar of Fangs, R1: name group 'Altar of Fangs' is unambiguous (Type-3 [3312, 3313, 3314], Type-1 [3374])
(2993,8,0,3374,3374), -- Altar of Fangs (Mythic Keystone): Altar of Fangs, R1: name group 'Altar of Fangs' is unambiguous (Type-3 [3312, 3313, 3314], Type-1 [3374])
(2993,23,0,3314,3314), -- Altar of Fangs (Mythic): Altar of Fangs, R1: name group 'Altar of Fangs' is unambiguous (Type-3 [3312, 3313, 3314], Type-1 [3374])
(2993,205,0,3312,3312); -- Altar of Fangs (Follower): Altar of Fangs, R1: name group 'Altar of Fangs' is unambiguous (Type-3 [3312, 3313, 3314], Type-1 [3374]) (follower runs the normal id)
