// Canonical SMART_EVENT / SMART_ACTION / SMART_TARGET tables for the
// smart_scripts row editor combo boxes.  Source of truth is
// src/server/game/AI/SmartScripts/SmartScriptMgr.h.  When upstream TC
// adds new enum entries (or repurposes "UNUSED, DO NOT REUSE" slots),
// refresh this file by re-copying the enum bodies.  Synced 2026-05-25.

#pragma once

namespace world_editor::app
{

struct SmartScriptEnumEntry
{
    int         value;
    char const* name;
};

// Mirror of enum SMART_EVENT (SmartScriptMgr.h:101).  Prefix
// SMART_EVENT_ stripped; UNUSED/DO-NOT-REUSE slots are preserved with
// their canonical name so an operator who sees a 12 in the column
// knows it was historically TARGET_HEALTH_PCT.  Includes the END
// sentinel (=91) so operators can sight-read the upstream count.
inline constexpr SmartScriptEnumEntry kSmartEvents[] = {
    {   0, "UPDATE_IC" },
    {   1, "UPDATE_OOC" },
    {   2, "HEALTH_PCT" },
    {   3, "MANA_PCT" },
    {   4, "AGGRO" },
    {   5, "KILL" },
    {   6, "DEATH" },
    {   7, "EVADE" },
    {   8, "SPELLHIT" },
    {   9, "RANGE" },
    {  10, "OOC_LOS" },
    {  11, "RESPAWN" },
    {  12, "TARGET_HEALTH_PCT (UNUSED)" },
    {  13, "VICTIM_CASTING" },
    {  14, "FRIENDLY_HEALTH (UNUSED)" },
    {  15, "FRIENDLY_IS_CC" },
    {  16, "FRIENDLY_MISSING_BUFF" },
    {  17, "SUMMONED_UNIT" },
    {  18, "TARGET_MANA_PCT (UNUSED)" },
    {  19, "ACCEPTED_QUEST" },
    {  20, "REWARD_QUEST" },
    {  21, "REACHED_HOME" },
    {  22, "RECEIVE_EMOTE" },
    {  23, "HAS_AURA" },
    {  24, "TARGET_BUFFED" },
    {  25, "RESET" },
    {  26, "IC_LOS" },
    {  27, "PASSENGER_BOARDED" },
    {  28, "PASSENGER_REMOVED" },
    {  29, "CHARMED" },
    {  30, "CHARMED_TARGET (UNUSED)" },
    {  31, "SPELLHIT_TARGET" },
    {  32, "DAMAGED" },
    {  33, "DAMAGED_TARGET" },
    {  34, "MOVEMENTINFORM" },
    {  35, "SUMMON_DESPAWNED" },
    {  36, "CORPSE_REMOVED" },
    {  37, "AI_INIT" },
    {  38, "DATA_SET" },
    {  39, "WAYPOINT_START (UNUSED)" },
    {  40, "WAYPOINT_REACHED" },
    {  41, "TRANSPORT_ADDPLAYER" },
    {  42, "TRANSPORT_ADDCREATURE" },
    {  43, "TRANSPORT_REMOVE_PLAYER" },
    {  44, "TRANSPORT_RELOCATE" },
    {  45, "INSTANCE_PLAYER_ENTER" },
    {  46, "AREATRIGGER_ENTER" },
    {  47, "QUEST_ACCEPTED" },
    {  48, "QUEST_OBJ_COMPLETION" },
    {  49, "QUEST_COMPLETION" },
    {  50, "QUEST_REWARDED" },
    {  51, "QUEST_FAIL" },
    {  52, "TEXT_OVER" },
    {  53, "RECEIVE_HEAL" },
    {  54, "JUST_SUMMONED" },
    {  55, "WAYPOINT_PAUSED" },
    {  56, "WAYPOINT_RESUMED" },
    {  57, "WAYPOINT_STOPPED" },
    {  58, "WAYPOINT_ENDED" },
    {  59, "TIMED_EVENT_TRIGGERED" },
    {  60, "UPDATE" },
    {  61, "LINK" },
    {  62, "GOSSIP_SELECT" },
    {  63, "JUST_CREATED" },
    {  64, "GOSSIP_HELLO" },
    {  65, "FOLLOW_COMPLETED" },
    {  66, "EVENT_PHASE_CHANGE (UNUSED)" },
    {  67, "IS_BEHIND_TARGET (UNUSED)" },
    {  68, "GAME_EVENT_START" },
    {  69, "GAME_EVENT_END" },
    {  70, "GO_LOOT_STATE_CHANGED" },
    {  71, "GO_EVENT_INFORM" },
    {  72, "ACTION_DONE" },
    {  73, "ON_SPELLCLICK" },
    {  74, "FRIENDLY_HEALTH_PCT" },
    {  75, "DISTANCE_CREATURE" },
    {  76, "DISTANCE_GAMEOBJECT" },
    {  77, "COUNTER_SET" },
    {  78, "SCENE_START" },
    {  79, "SCENE_TRIGGER" },
    {  80, "SCENE_CANCEL" },
    {  81, "SCENE_COMPLETE" },
    {  82, "SUMMONED_UNIT_DIES" },
    {  83, "ON_SPELL_CAST" },
    {  84, "ON_SPELL_FAILED" },
    {  85, "ON_SPELL_START" },
    {  86, "ON_DESPAWN" },
    {  87, "SEND_EVENT_TRIGGER" },
    {  88, "AREATRIGGER_EXIT" },
    {  89, "ON_AURA_APPLIED" },
    {  90, "ON_AURA_REMOVED" },
    {  91, "END (sentinel)" },
};

// Mirror of enum SMART_ACTION (SmartScriptMgr.h:456).  Prefix
// SMART_ACTION_ stripped.  Multiple slots are flagged UNUSED or
// DEPRECATED in the upstream header -- preserved verbatim so a row
// that historically used (e.g.) action 18 SET_UNIT_FLAG still
// round-trips with its number visible.
inline constexpr SmartScriptEnumEntry kSmartActions[] = {
    {   0, "NONE" },
    {   1, "TALK" },
    {   2, "SET_FACTION" },
    {   3, "MORPH_TO_ENTRY_OR_MODEL" },
    {   4, "SOUND" },
    {   5, "PLAY_EMOTE" },
    {   6, "FAIL_QUEST" },
    {   7, "OFFER_QUEST" },
    {   8, "SET_REACT_STATE" },
    {   9, "ACTIVATE_GOBJECT" },
    {  10, "RANDOM_EMOTE" },
    {  11, "CAST" },
    {  12, "SUMMON_CREATURE" },
    {  13, "THREAT_SINGLE_PCT" },
    {  14, "THREAT_ALL_PCT" },
    {  15, "CALL_AREAEXPLOREDOREVENTHAPPENS (UNUSED)" },
    {  16, "SET_INGAME_PHASE_GROUP" },
    {  17, "SET_EMOTE_STATE" },
    {  18, "SET_UNIT_FLAG (UNUSED)" },
    {  19, "REMOVE_UNIT_FLAG (UNUSED)" },
    {  20, "AUTO_ATTACK" },
    {  21, "ALLOW_COMBAT_MOVEMENT" },
    {  22, "SET_EVENT_PHASE" },
    {  23, "INC_EVENT_PHASE" },
    {  24, "EVADE" },
    {  25, "FLEE_FOR_ASSIST" },
    {  26, "CALL_GROUPEVENTHAPPENS (UNUSED)" },
    {  27, "COMBAT_STOP" },
    {  28, "REMOVEAURASFROMSPELL" },
    {  29, "FOLLOW" },
    {  30, "RANDOM_PHASE" },
    {  31, "RANDOM_PHASE_RANGE" },
    {  32, "RESET_GOBJECT" },
    {  33, "CALL_KILLEDMONSTER" },
    {  34, "SET_INST_DATA" },
    {  35, "SET_INST_DATA64" },
    {  36, "UPDATE_TEMPLATE" },
    {  37, "DIE" },
    {  38, "SET_IN_COMBAT_WITH_ZONE" },
    {  39, "CALL_FOR_HELP" },
    {  40, "SET_SHEATH" },
    {  41, "FORCE_DESPAWN" },
    {  42, "SET_INVINCIBILITY_HP_LEVEL" },
    {  43, "MOUNT_TO_ENTRY_OR_MODEL" },
    {  44, "SET_INGAME_PHASE_ID" },
    {  45, "SET_DATA" },
    {  46, "ATTACK_STOP" },
    {  47, "SET_VISIBILITY" },
    {  48, "SET_ACTIVE" },
    {  49, "ATTACK_START" },
    {  50, "SUMMON_GO" },
    {  51, "KILL_UNIT" },
    {  52, "ACTIVATE_TAXI" },
    {  53, "WP_START" },
    {  54, "WP_PAUSE" },
    {  55, "WP_STOP" },
    {  56, "ADD_ITEM" },
    {  57, "REMOVE_ITEM" },
    {  58, "INSTALL_AI_TEMPLATE (UNUSED)" },
    {  59, "SET_RUN" },
    {  60, "SET_DISABLE_GRAVITY" },
    {  61, "SET_SWIM (UNUSED)" },
    {  62, "TELEPORT" },
    {  63, "SET_COUNTER" },
    {  64, "STORE_TARGET_LIST" },
    {  65, "WP_RESUME" },
    {  66, "SET_ORIENTATION" },
    {  67, "CREATE_TIMED_EVENT" },
    {  68, "PLAYMOVIE" },
    {  69, "MOVE_TO_POS" },
    {  70, "ENABLE_TEMP_GOBJ" },
    {  71, "EQUIP" },
    {  72, "CLOSE_GOSSIP" },
    {  73, "TRIGGER_TIMED_EVENT" },
    {  74, "REMOVE_TIMED_EVENT" },
    {  75, "ADD_AURA (UNUSED)" },
    {  76, "OVERRIDE_SCRIPT_BASE_OBJECT (UNUSED)" },
    {  77, "RESET_SCRIPT_BASE_OBJECT (UNUSED)" },
    {  78, "CALL_SCRIPT_RESET" },
    {  79, "SET_RANGED_MOVEMENT" },
    {  80, "CALL_TIMED_ACTIONLIST" },
    {  81, "SET_NPC_FLAG" },
    {  82, "ADD_NPC_FLAG" },
    {  83, "REMOVE_NPC_FLAG" },
    {  84, "SIMPLE_TALK" },
    {  85, "SELF_CAST" },
    {  86, "CROSS_CAST" },
    {  87, "CALL_RANDOM_TIMED_ACTIONLIST" },
    {  88, "CALL_RANDOM_RANGE_TIMED_ACTIONLIST" },
    {  89, "RANDOM_MOVE" },
    {  90, "SET_UNIT_FIELD_BYTES_1" },
    {  91, "REMOVE_UNIT_FIELD_BYTES_1" },
    {  92, "INTERRUPT_SPELL" },
    {  93, "SEND_GO_CUSTOM_ANIM (UNUSED)" },
    {  94, "SET_DYNAMIC_FLAG (UNUSED)" },
    {  95, "ADD_DYNAMIC_FLAG (UNUSED)" },
    {  96, "REMOVE_DYNAMIC_FLAG (UNUSED)" },
    {  97, "JUMP_TO_POS" },
    {  98, "SEND_GOSSIP_MENU" },
    {  99, "GO_SET_LOOT_STATE" },
    { 100, "SEND_TARGET_TO_TARGET" },
    { 101, "SET_HOME_POS" },
    { 102, "SET_HEALTH_REGEN" },
    { 103, "SET_ROOT" },
    { 104, "SET_GO_FLAG (UNUSED)" },
    { 105, "ADD_GO_FLAG (UNUSED)" },
    { 106, "REMOVE_GO_FLAG (UNUSED)" },
    { 107, "SUMMON_CREATURE_GROUP" },
    { 108, "SET_POWER" },
    { 109, "ADD_POWER" },
    { 110, "REMOVE_POWER" },
    { 111, "GAME_EVENT_STOP" },
    { 112, "GAME_EVENT_START" },
    { 113, "START_CLOSEST_WAYPOINT" },
    { 114, "MOVE_OFFSET" },
    { 115, "RANDOM_SOUND" },
    { 116, "SET_CORPSE_DELAY" },
    { 117, "DISABLE_EVADE" },
    { 118, "GO_SET_GO_STATE" },
    { 119, "SET_CAN_FLY (UNUSED)" },
    { 120, "REMOVE_AURAS_BY_TYPE (UNUSED)" },
    { 121, "SET_SIGHT_DIST (UNUSED)" },
    { 122, "FLEE (UNUSED)" },
    { 123, "ADD_THREAT" },
    { 124, "LOAD_EQUIPMENT" },
    { 125, "TRIGGER_RANDOM_TIMED_EVENT" },
    { 126, "REMOVE_ALL_GAMEOBJECTS (UNUSED)" },
    { 127, "PAUSE_MOVEMENT" },
    { 128, "PLAY_ANIMKIT" },
    { 129, "SCENE_PLAY" },
    { 130, "SCENE_CANCEL" },
    { 131, "SPAWN_SPAWNGROUP" },
    { 132, "DESPAWN_SPAWNGROUP" },
    { 133, "RESPAWN_BY_SPAWNID" },
    { 134, "INVOKER_CAST" },
    { 135, "PLAY_CINEMATIC" },
    { 136, "SET_MOVEMENT_SPEED" },
    { 137, "PLAY_SPELL_VISUAL_KIT" },
    { 138, "OVERRIDE_LIGHT" },
    { 139, "OVERRIDE_WEATHER" },
    { 140, "SET_AI_ANIM_KIT (DEPRECATED)" },
    { 141, "SET_HOVER" },
    { 142, "SET_HEALTH_PCT" },
    { 143, "CREATE_CONVERSATION" },
    { 144, "SET_IMMUNE_PC" },
    { 145, "SET_IMMUNE_NPC" },
    { 146, "SET_UNINTERACTIBLE" },
    { 147, "ACTIVATE_GAMEOBJECT" },
    { 148, "ADD_TO_STORED_TARGET_LIST" },
    { 149, "BECOME_PERSONAL_CLONE_FOR_PLAYER" },
    { 150, "TRIGGER_GAME_EVENT" },
    { 151, "DO_ACTION" },
    { 152, "COMPLETE_QUEST" },
    { 153, "CREDIT_QUEST_OBJECTIVE_TALK_TO" },
    { 154, "DESTROY_CONVERSATION" },
    { 155, "ENTER_VEHICLE" },
    { 156, "BOARD_PASSENGER" },
    { 157, "EXIT_VEHICLE" },
    { 158, "RESUME_MOVEMENT" },
    { 159, "FALL" },
    { 160, "END (sentinel)" },
};

// Mirror of enum SMARTAI_TARGETS (SmartScriptMgr.h:1300).  Prefix
// SMART_TARGET_ stripped.  The upstream enum is named SMARTAI_TARGETS
// (note the AI suffix) but every value is spelled SMART_TARGET_*.
inline constexpr SmartScriptEnumEntry kSmartTargets[] = {
    {   0, "NONE" },
    {   1, "SELF" },
    {   2, "VICTIM" },
    {   3, "HOSTILE_SECOND_AGGRO" },
    {   4, "HOSTILE_LAST_AGGRO" },
    {   5, "HOSTILE_RANDOM" },
    {   6, "HOSTILE_RANDOM_NOT_TOP" },
    {   7, "ACTION_INVOKER" },
    {   8, "POSITION" },
    {   9, "CREATURE_RANGE" },
    {  10, "CREATURE_GUID" },
    {  11, "CREATURE_DISTANCE" },
    {  12, "STORED" },
    {  13, "GAMEOBJECT_RANGE" },
    {  14, "GAMEOBJECT_GUID" },
    {  15, "GAMEOBJECT_DISTANCE" },
    {  16, "INVOKER_PARTY" },
    {  17, "PLAYER_RANGE" },
    {  18, "PLAYER_DISTANCE" },
    {  19, "CLOSEST_CREATURE" },
    {  20, "CLOSEST_GAMEOBJECT" },
    {  21, "CLOSEST_PLAYER" },
    {  22, "ACTION_INVOKER_VEHICLE" },
    {  23, "OWNER_OR_SUMMONER" },
    {  24, "THREAT_LIST" },
    {  25, "CLOSEST_ENEMY" },
    {  26, "CLOSEST_FRIENDLY" },
    {  27, "LOOT_RECIPIENTS" },
    {  28, "FARTHEST" },
    {  29, "VEHICLE_PASSENGER" },
    {  30, "CLOSEST_UNSPAWNED_GAMEOBJECT" },
    {  31, "END (sentinel)" },
};

} // namespace world_editor::app
