#!/usr/bin/env python3
"""Generate FlagMetadata.gen.h from TrinityCore's UnitDefines.h.

The world_editor's spawn Flags tab presents npcflag / unit_flags / unit_flags2 /
unit_flags3 as named checkbox lists instead of raw hex.  The friendly names come
straight from the `// TITLE ...` comments TC already maintains on each flag (the
same source its EnumUtils uses), so the editor's labels can never drift from
core.  Parsed at BUILD TIME, exactly like gen_smartai_metadata.py.

Usage: gen_flag_metadata.py <UnitDefines.h> <out.h>
"""
import re
import sys

# (enumName, arrayName, prefix) for every flag enum we surface in the picker.
ENUMS = [
    ("UnitFlags",  "kUnitFlags",  "UNIT_FLAG_"),
    ("UnitFlags2", "kUnitFlags2", "UNIT_FLAG2_"),
    ("UnitFlags3", "kUnitFlags3", "UNIT_FLAG3_"),
    ("NPCFlags",   "kNpcFlags",   "UNIT_NPC_FLAG_"),
    ("NPCFlags2",  "kNpcFlags2",  "UNIT_NPC_FLAG_2_"),
]

# NAME = 0xHEX , with an optional trailing // comment.  Composite entries
# (DISALLOWED/ALLOWED/MASK = (A | B ...)) are not literal hex so they never
# match -- exactly what we want.
ENTRY_RE = re.compile(
    r'^\s*([A-Z][A-Z0-9_]+)\s*=\s*(0x[0-9A-Fa-f]+)\s*,?\s*(?://\s*(.*?))?\s*$')


def c_escape(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')


def parse_enum(text, enum_name):
    # Slice from "enum <NAME> : uint32 {" to the next "};".
    m = re.search(r'enum\s+' + re.escape(enum_name) + r'\s*:[^\{]*\{', text)
    if not m:
        m = re.search(r'enum\s+' + re.escape(enum_name) + r'\s*\{', text)
    if not m:
        return []
    start = m.end()
    end = text.find('};', start)
    body = text[start:end]
    out = []
    for line in body.splitlines():
        em = ENTRY_RE.match(line)
        if not em:
            continue
        name = em.group(1)
        value = int(em.group(2), 16)
        comment = (em.group(3) or '').strip()
        if value == 0:
            continue  # NONE sentinels carry no checkbox
        out.append((value, name, comment))
    return out


def friendly_label(name, prefix, comment):
    # Prefer the human TITLE text TC documents on the flag.
    m = re.match(r'TITLE\s+(.*?)(?:\s+DESCRIPTION\b.*)?$', comment)
    if m and m.group(1).strip():
        return m.group(1).strip()
    base = name[len(prefix):] if name.startswith(prefix) else name
    return base.replace('_', ' ').title()


def read(path):
    with open(path, 'r', encoding='utf-8', errors='replace') as f:
        return f.read()


def main():
    src, dst = sys.argv[1], sys.argv[2]
    text = read(src)

    lines = []
    lines.append('// AUTO-GENERATED by codegen/gen_flag_metadata.py from core')
    lines.append('// UnitDefines.h. DO NOT EDIT.')
    lines.append('#pragma once')
    lines.append('#include <cstdint>')
    lines.append('namespace world_editor::flags {')
    lines.append('struct FlagEntry { uint32_t value; char const* name; char const* label; };')

    counts = {}
    for enum_name, arr, prefix in ENUMS:
        entries = parse_enum(text, enum_name)
        counts[arr] = len(entries)
        lines.append(f'// {enum_name}: {len(entries)} entries')
        lines.append(f'inline constexpr FlagEntry {arr}[] = {{')
        for value, name, comment in entries:
            label = friendly_label(name, prefix, comment)
            lines.append(
                f'    {{ 0x{value:08X}u, "{c_escape(name)}", "{c_escape(label)}" }},')
        if not entries:
            lines.append('    { 0u, "", "" },')
        lines.append('};')
        lines.append(f'inline constexpr int {arr}Count = {len(entries)};')

    lines.append('} // namespace world_editor::flags')
    lines.append('')

    with open(dst, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    sys.stderr.write(f'gen_flag_metadata: {counts}\n')


if __name__ == '__main__':
    main()
