#!/usr/bin/env python3
"""Generate SmartAiMetadata.gen.h from TrinityCore core headers.

The world_editor's SmartAI + Conditions authoring needs, for every enum value,
its name and the meaning of its parameters. TC documents those in the trailing
// comment of each enum entry. Parsing the headers at BUILD TIME means the
editor's labels can never drift from core (the old hand-maintained
SmartScriptEnumTables.h / ConditionEnumTables.h could).

Usage: gen_smartai_metadata.py <SmartScriptMgr.h> <out.h> [ConditionMgr.h]
"""
import re
import sys

# (sourceKey, enumName, arrayName, prefix). sourceKey indexes the source files
# below; 'smart' = SmartScriptMgr.h (argv[1]), 'cond' = ConditionMgr.h (argv[3]).
ENUMS = [
    ("smart", "SMART_EVENT",     "kSmartEvents",  "SMART_EVENT_"),
    ("smart", "SMART_ACTION",    "kSmartActions", "SMART_ACTION_"),
    ("smart", "SMARTAI_TARGETS", "kSmartTargets", "SMART_TARGET_"),
    ("cond",  "ConditionTypes",  "kConditions",   "CONDITION_"),
]

# Any UPPER_SNAKE enum entry assigned a literal integer, with an optional
# trailing // comment. We only ever apply this within a sliced enum body.
ENTRY_RE = re.compile(
    r'^\s*([A-Z][A-Z0-9_]+)\s*=\s*(\d+)\s*,?\s*(?://\s*(.*?))?\s*$')


def c_escape(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')


def parse_enum(text, enum_name):
    # Slice from "enum <NAME>" to the next "};".
    m = re.search(r'enum\s+' + re.escape(enum_name) + r'\s*\{', text)
    if not m:
        return []
    start = m.end()
    end = text.find('};', start)
    body = text[start:end]
    out = []
    for line in body.splitlines():
        em = ENTRY_RE.match(line)
        if not em:
            continue
        name, value, comment = em.group(1), int(em.group(2)), (em.group(3) or '').strip()
        out.append((value, name, comment))
    return out


def short_label(name, prefix):
    base = name[len(prefix):] if name.startswith(prefix) else name
    return base.replace('_', ' ').title()


def read(path):
    with open(path, 'r', encoding='utf-8', errors='replace') as f:
        return f.read()


def main():
    dst = sys.argv[2]
    texts = {'smart': read(sys.argv[1])}
    if len(sys.argv) > 3 and sys.argv[3]:
        texts['cond'] = read(sys.argv[3])

    lines = []
    lines.append('// AUTO-GENERATED by codegen/gen_smartai_metadata.py from core headers')
    lines.append('// (SmartScriptMgr.h, ConditionMgr.h). DO NOT EDIT.')
    lines.append('#pragma once')
    lines.append('namespace world_editor::smartai {')
    lines.append('struct MetaEntry { int value; char const* name; char const* label; char const* params; };')

    counts = {}
    for src_key, enum_name, arr, prefix in ENUMS:
        text = texts.get(src_key)
        entries = parse_enum(text, enum_name) if text else []
        counts[arr] = len(entries)
        lines.append(f'// {enum_name}: {len(entries)} entries')
        lines.append(f'inline constexpr MetaEntry {arr}[] = {{')
        for value, name, comment in entries:
            label = short_label(name, prefix)
            lines.append(
                f'    {{ {value}, "{c_escape(name)}", "{c_escape(label)}", "{c_escape(comment)}" }},')
        # Guard against an empty array (C++ forbids zero-size arrays).
        if not entries:
            lines.append('    { -1, "", "", "" },')
        lines.append('};')
        lines.append(f'inline constexpr int {arr}Count = {len(entries)};')

    lines.append('} // namespace world_editor::smartai')
    lines.append('')

    with open(dst, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    sys.stderr.write(f'gen_smartai_metadata: {counts}\n')


if __name__ == '__main__':
    main()
