-- ========================================================================================
-- CONTENT SLICE -- Waking Shores (map 2927) :: Dragonflight intro quest chain -- scripts
-- ========================================================================================
-- Generated 2026-09-09 by TCHarvest tools/author_chain_slice.py
-- Sources: rpe_a4_proj: dump_12.1.0.69587_2026-09-09_22-24-58.pkt + TCHarvest.lua + combat log; wpp_alliance; wpp_alliance2; wpp_alliance3; wpp_horde; rpe_h2_proj
--
-- STARTING POINT, tunable as more captures arrive (user decision 2026-09-04). Single-capture
-- facts are shipped LIVE here and tagged [LOW]; two-capture agreement is tagged [HIGH].
-- Every row names the wire tick it was derived from. Capture-absence is NEVER a deletion:
-- nothing here removes realm content that the captures did not see.
-- Rows marked 'depends: C++' need src/server/scripts/DragonIsles/zone_the_waking_shores.cpp
-- built into worldserver -- apply them WITH the rebuild, not before (see tc-worldbuilding-solutions).
-- Chain walked by the capturer (turn-in order): 90882, 90883, 90885, 90886, 90887, 90888, 90893, 90895, 90896, 90897, 92028
-- ========================================================================================


-- ----------------------------------------------------------------------------------------
-- 1. quest_template_addon.PrevQuestID -- inferred from availability snapshots vs turn-in order
--   synth/quest_prereq.py: a quest that became offerable only after another was turned in
--   (per giver, per snapshot). HIGH = a single clean seq transition; LOW = a set of candidates.
-- ----------------------------------------------------------------------------------------

-- ----------------------------------------------------------------------------------------
-- 2. npc_spellclick_spells -- the InteractSpellId the client was actually given (CMSG_SPELL_CLICK + cast)
--   sniff spellclick channel; realm rows carried a different spell of the same name/family.
--   The whelpling's realm SmartAI credited on GOSSIP_HELLO, which a spellclick-only NPC never
--   fires -- rewired to ON_SPELLCLICK (73) so the objective can complete.
-- ----------------------------------------------------------------------------------------
-- [LOW] rpe_a4_proj: creature 244956 (Prized Pumpkin) clicked -> spell 1236722 'Recovering'; realm registers [1236771] (same family, different id)
DELETE FROM `npc_spellclick_spells` WHERE `npc_entry`=244956;
INSERT INTO `npc_spellclick_spells` (`npc_entry`, `spell_id`, `cast_flags`, `user_type`) VALUES (244956, 1236722, 0, 0);
UPDATE `creature_template` SET `npcflag`=`npcflag`|16777216 WHERE `entry`=244956;
-- [LOW] rpe_a4_proj: creature 249269 (Worn Catapult) clicked -> spell 1248670 'Placing Rune'; realm registers [1248649] (same family, different id)
DELETE FROM `npc_spellclick_spells` WHERE `npc_entry`=249269;
INSERT INTO `npc_spellclick_spells` (`npc_entry`, `spell_id`, `cast_flags`, `user_type`) VALUES (249269, 1248670, 0, 0);
UPDATE `creature_template` SET `npcflag`=`npcflag`|16777216 WHERE `entry`=249269;

-- ----------------------------------------------------------------------------------------
-- 3. conversation_template / conversation_actors / conversation_line_template -- every Conversation the server created
--   sniff conversation channel; the realm had NONE of these ids. FirstLineId chains through
--   ConversationLine.db2 (all 68 first lines verified present in the 69587 client DB2).
--   Talking heads (Wrathion, Toddy, Naleidea) ARE conversations with a UiCameraID -- no other table.
-- ----------------------------------------------------------------------------------------
INSERT INTO `conversation_template` (`Id`, `FirstLineId`) VALUES (30650, 84456) ON DUPLICATE KEY UPDATE `Id`=VALUES(`Id`), `FirstLineId`=VALUES(`FirstLineId`);
-- conversation_actors: world-object actors resolved to realm spawn guids (see comments)
INSERT INTO `conversation_actors` (`ConversationId`, `ConversationActorId`, `ConversationActorGuid`, `Idx`, `CreatureId`, `CreatureDisplayInfoId`, `NoActorObject`, `ActivePlayerObject`) VALUES (29727, 0, 0, 0, 0, 0, 0, 1) ON DUPLICATE KEY UPDATE `CreatureId`=VALUES(`CreatureId`), `CreatureDisplayInfoId`=VALUES(`CreatureDisplayInfoId`);
-- REVIEW (not applied): conversation 29730 actor 0: world-object speaker = creature None (no realm spawn on this map) -- set ConversationActorGuid by hand
-- INSERT INTO `conversation_actors` (`ConversationId`, `ConversationActorId`, `ConversationActorGuid`, `Idx`, `CreatureId`, `CreatureDisplayInfoId`, `NoActorObject`, `ActivePlayerObject`) VALUES (29730, 107917, 0, 0, 0, 0, 0, 0);
-- [LOW] conversation 29725 actor 0: world-object speaker = creature 244642 -> spawn guid 8000001 (the realm's only spawn of 244642)
INSERT INTO `conversation_actors` (`ConversationId`, `ConversationActorId`, `ConversationActorGuid`, `Idx`, `CreatureId`, `CreatureDisplayInfoId`, `NoActorObject`, `ActivePlayerObject`) VALUES (29725, 107908, 8000001, 0, 0, 0, 0, 0) ON DUPLICATE KEY UPDATE `ConversationActorGuid`=VALUES(`ConversationActorGuid`);
-- [LOW] conversation 29726 actor 0: world-object speaker = creature 244643 -> spawn guid 8000000 (the realm's only spawn of 244643)
INSERT INTO `conversation_actors` (`ConversationId`, `ConversationActorId`, `ConversationActorGuid`, `Idx`, `CreatureId`, `CreatureDisplayInfoId`, `NoActorObject`, `ActivePlayerObject`) VALUES (29726, 107909, 8000000, 0, 0, 0, 0, 0) ON DUPLICATE KEY UPDATE `ConversationActorGuid`=VALUES(`ConversationActorGuid`);
-- [LOW] conversation 29727 actor 1: world-object speaker = creature 244642 -> spawn guid 8000001 (the realm's only spawn of 244642)
INSERT INTO `conversation_actors` (`ConversationId`, `ConversationActorId`, `ConversationActorGuid`, `Idx`, `CreatureId`, `CreatureDisplayInfoId`, `NoActorObject`, `ActivePlayerObject`) VALUES (29727, 107910, 8000001, 1, 0, 0, 0, 0) ON DUPLICATE KEY UPDATE `ConversationActorGuid`=VALUES(`ConversationActorGuid`);
-- [LOW] conversation 29728 actor 0: world-object speaker = creature 244655 -> spawn guid 8000027 (the realm's only spawn of 244655)
INSERT INTO `conversation_actors` (`ConversationId`, `ConversationActorId`, `ConversationActorGuid`, `Idx`, `CreatureId`, `CreatureDisplayInfoId`, `NoActorObject`, `ActivePlayerObject`) VALUES (29728, 107913, 8000027, 0, 0, 0, 0, 0) ON DUPLICATE KEY UPDATE `ConversationActorGuid`=VALUES(`ConversationActorGuid`);
-- REVIEW (not applied): conversation 30650 actor 0: world-object speaker = creature 249456 (no realm spawn on this map) -- set ConversationActorGuid by hand
-- INSERT INTO `conversation_actors` (`ConversationId`, `ConversationActorId`, `ConversationActorGuid`, `Idx`, `CreatureId`, `CreatureDisplayInfoId`, `NoActorObject`, `ActivePlayerObject`) VALUES (30650, 109811, 0, 0, 0, 0, 0, 0);
-- [LOW] conversation 30602 actor 0: world-object speaker = creature 244709 -> spawn guid 8000138 (the realm's only spawn of 244709)
INSERT INTO `conversation_actors` (`ConversationId`, `ConversationActorId`, `ConversationActorGuid`, `Idx`, `CreatureId`, `CreatureDisplayInfoId`, `NoActorObject`, `ActivePlayerObject`) VALUES (30602, 109705, 8000138, 0, 0, 0, 0, 0) ON DUPLICATE KEY UPDATE `ConversationActorGuid`=VALUES(`ConversationActorGuid`);
-- [LOW] conversation 29735 actor 0: world-object speaker = creature 244666 -> spawn guid 8000139 (the realm's only spawn of 244666)
INSERT INTO `conversation_actors` (`ConversationId`, `ConversationActorId`, `ConversationActorGuid`, `Idx`, `CreatureId`, `CreatureDisplayInfoId`, `NoActorObject`, `ActivePlayerObject`) VALUES (29735, 107938, 8000139, 0, 0, 0, 0, 0) ON DUPLICATE KEY UPDATE `ConversationActorGuid`=VALUES(`ConversationActorGuid`);
-- [LOW] conversation 29735 actor 1: world-object speaker = creature 244667 -> spawn guid 8000140 (the realm's only spawn of 244667)
INSERT INTO `conversation_actors` (`ConversationId`, `ConversationActorId`, `ConversationActorGuid`, `Idx`, `CreatureId`, `CreatureDisplayInfoId`, `NoActorObject`, `ActivePlayerObject`) VALUES (29735, 107937, 8000140, 1, 0, 0, 0, 0) ON DUPLICATE KEY UPDATE `ConversationActorGuid`=VALUES(`ConversationActorGuid`);
-- world-object actors: 7 resolved, 2 left for review

-- ----------------------------------------------------------------------------------------
-- 4. SmartQuest triggers -- WHEN each conversation was created (quest status <-> create tick)
--   Source-type 5 (quest) SmartAI: 47 QUEST_ACCEPTED, 48 QUEST_OBJ_COMPLETION(objective id),
--   49 QUEST_COMPLETION; action 143 CREATE_CONVERSATION on the invoking player (target 7).
--   delta = ticks between the quest status frame and SMSG_UPDATE_OBJECT creating the conversation.
--   Base object is the quest, so this fires wherever the player is -- matching the wire, where
--   the conversations were personal (created for the player, not by an NPC in range).
-- ----------------------------------------------------------------------------------------
-- quest 92028
UPDATE `quest_template_addon` SET `ScriptName`='SmartQuest' WHERE `ID`=92028;
-- [LOW] on OBJECTIVE 463995 complete (credit object 249351, storage 0): quest 92028 'Pardon the Interruption' -> conversation 30650 (statusTick=1962850 createTick=1962951 delta=101)
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `action_param7`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (92028, 5, 0, 0, 48, 0, 100, 0, 463995, 0, 0, 0, 0, 143, 30650, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'Quest 92028 - On objective 463995 complete - Create conversation 30650') ON DUPLICATE KEY UPDATE `event_type`=VALUES(`event_type`), `event_phase_mask`=VALUES(`event_phase_mask`), `event_chance`=VALUES(`event_chance`), `event_flags`=VALUES(`event_flags`), `event_param1`=VALUES(`event_param1`), `event_param2`=VALUES(`event_param2`), `event_param3`=VALUES(`event_param3`), `event_param4`=VALUES(`event_param4`), `event_param5`=VALUES(`event_param5`), `action_type`=VALUES(`action_type`), `action_param1`=VALUES(`action_param1`), `action_param2`=VALUES(`action_param2`), `action_param3`=VALUES(`action_param3`), `action_param4`=VALUES(`action_param4`), `action_param5`=VALUES(`action_param5`), `action_param6`=VALUES(`action_param6`), `action_param7`=VALUES(`action_param7`), `target_type`=VALUES(`target_type`), `target_param1`=VALUES(`target_param1`), `target_param2`=VALUES(`target_param2`), `target_param3`=VALUES(`target_param3`), `target_param4`=VALUES(`target_param4`), `target_x`=VALUES(`target_x`), `target_y`=VALUES(`target_y`), `target_z`=VALUES(`target_z`), `target_o`=VALUES(`target_o`), `comment`=VALUES(`comment`);

-- ----------------------------------------------------------------------------------------
-- 5. Combat SmartAI -- what each creature cast against the capturer (combat log, advanced logging)
--   combatlog channel: first cast at ~100% HP = AGGRO cast; a spell seen only at low HP = HEALTH_PCT.
--   Casts observed only at 0% HP are the log's death noise or a 0-HP trigger creature -> REVIEW.
--   Cadence/repeat timers are NOT observable from one pull: AGGRO rows fire once per combat.
--   [HIGH] = the same entry cast the same spell in another capture's combat log.
-- ----------------------------------------------------------------------------------------
-- EXCLUDED entry 3527 (?): capture artifact, SUMMONED in this capture's combat log (SPELL_SUMMON roster) -- never a zone creature
-- EXCLUDED entry 61245 (?): capture artifact, SUMMONED in this capture's combat log (SPELL_SUMMON roster) -- never a zone creature
-- EXCLUDED entry 77936 (?): capture artifact, SUMMONED in this capture's combat log (SPELL_SUMMON roster) -- never a zone creature
-- EXCLUDED entry 143622 (?): capture artifact, SUMMONED in this capture's combat log (SPELL_SUMMON roster) -- never a zone creature
-- EXCLUDED entry 237409 (?): capture artifact, SUMMONED in this capture's combat log (SPELL_SUMMON roster) -- never a zone creature
-- creature 244670 'Gnoll Bowblaster' realm AIName='SmartAI' ScriptName=''
-- [HIGH] combatlog: entry 244670 UNIT_DIED, last observed cast spell 372369
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `action_param7`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (244670, 0, 1, 0, 6, 0, 100, 0, 0, 0, 0, 0, 0, 11, 372369, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Gnoll Bowblaster - On HP 0-0% - Cast 372369 [HIGH] (rpe_a4_proj combat log)') ON DUPLICATE KEY UPDATE `event_type`=VALUES(`event_type`), `event_phase_mask`=VALUES(`event_phase_mask`), `event_chance`=VALUES(`event_chance`), `event_flags`=VALUES(`event_flags`), `event_param1`=VALUES(`event_param1`), `event_param2`=VALUES(`event_param2`), `event_param3`=VALUES(`event_param3`), `event_param4`=VALUES(`event_param4`), `event_param5`=VALUES(`event_param5`), `action_type`=VALUES(`action_type`), `action_param1`=VALUES(`action_param1`), `action_param2`=VALUES(`action_param2`), `action_param3`=VALUES(`action_param3`), `action_param4`=VALUES(`action_param4`), `action_param5`=VALUES(`action_param5`), `action_param6`=VALUES(`action_param6`), `action_param7`=VALUES(`action_param7`), `target_type`=VALUES(`target_type`), `target_param1`=VALUES(`target_param1`), `target_param2`=VALUES(`target_param2`), `target_param3`=VALUES(`target_param3`), `target_param4`=VALUES(`target_param4`), `target_x`=VALUES(`target_x`), `target_y`=VALUES(`target_y`), `target_z`=VALUES(`target_z`), `target_o`=VALUES(`target_o`), `comment`=VALUES(`comment`);
-- creature 244672 'Gnoll Bruiser' realm AIName='' ScriptName=''
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=244672 AND `AIName`='' AND `ScriptName`='';
-- [HIGH] combatlog: entry 244672 UNIT_DIED, last observed cast spell 1270764
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `action_param7`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (244672, 0, 0, 0, 6, 0, 100, 0, 0, 0, 0, 0, 0, 11, 1270764, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Gnoll Bruiser - On HP 0-0% - Cast 1270764 [HIGH] (rpe_a4_proj combat log)') ON DUPLICATE KEY UPDATE `event_type`=VALUES(`event_type`), `event_phase_mask`=VALUES(`event_phase_mask`), `event_chance`=VALUES(`event_chance`), `event_flags`=VALUES(`event_flags`), `event_param1`=VALUES(`event_param1`), `event_param2`=VALUES(`event_param2`), `event_param3`=VALUES(`event_param3`), `event_param4`=VALUES(`event_param4`), `event_param5`=VALUES(`event_param5`), `action_type`=VALUES(`action_type`), `action_param1`=VALUES(`action_param1`), `action_param2`=VALUES(`action_param2`), `action_param3`=VALUES(`action_param3`), `action_param4`=VALUES(`action_param4`), `action_param5`=VALUES(`action_param5`), `action_param6`=VALUES(`action_param6`), `action_param7`=VALUES(`action_param7`), `target_type`=VALUES(`target_type`), `target_param1`=VALUES(`target_param1`), `target_param2`=VALUES(`target_param2`), `target_param3`=VALUES(`target_param3`), `target_param4`=VALUES(`target_param4`), `target_x`=VALUES(`target_x`), `target_y`=VALUES(`target_y`), `target_z`=VALUES(`target_z`), `target_o`=VALUES(`target_o`), `comment`=VALUES(`comment`);
-- creature 244674 'Ogre Destroyer' realm AIName='' ScriptName=''
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=244674 AND `AIName`='' AND `ScriptName`='';
-- [HIGH] combatlog: entry 244674 UNIT_DIED, last observed cast spell 316890
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `action_param7`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (244674, 0, 0, 0, 6, 0, 100, 0, 0, 0, 0, 0, 0, 11, 316890, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Ogre Destroyer - On HP 0-0% - Cast 316890 [HIGH] (rpe_a4_proj combat log)') ON DUPLICATE KEY UPDATE `event_type`=VALUES(`event_type`), `event_phase_mask`=VALUES(`event_phase_mask`), `event_chance`=VALUES(`event_chance`), `event_flags`=VALUES(`event_flags`), `event_param1`=VALUES(`event_param1`), `event_param2`=VALUES(`event_param2`), `event_param3`=VALUES(`event_param3`), `event_param4`=VALUES(`event_param4`), `event_param5`=VALUES(`event_param5`), `action_type`=VALUES(`action_type`), `action_param1`=VALUES(`action_param1`), `action_param2`=VALUES(`action_param2`), `action_param3`=VALUES(`action_param3`), `action_param4`=VALUES(`action_param4`), `action_param5`=VALUES(`action_param5`), `action_param6`=VALUES(`action_param6`), `action_param7`=VALUES(`action_param7`), `target_type`=VALUES(`target_type`), `target_param1`=VALUES(`target_param1`), `target_param2`=VALUES(`target_param2`), `target_param3`=VALUES(`target_param3`), `target_param4`=VALUES(`target_param4`), `target_x`=VALUES(`target_x`), `target_y`=VALUES(`target_y`), `target_z`=VALUES(`target_z`), `target_o`=VALUES(`target_o`), `comment`=VALUES(`comment`);
-- creature 244675 'Runk' realm AIName='SmartAI' ScriptName=''
-- [HIGH] combatlog: entry 244675 spell 305913 cast only observed at <= 20% HP (n=2); fires once while HP is in [0,20]% -- NOT_REPEATABLE (v1 does not infer a real repeat cadence f
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `action_param7`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (244675, 0, 5, 0, 2, 0, 100, 1, 0, 20, 0, 0, 0, 11, 305913, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Runk - On HP 0-20% - Cast 305913 [HIGH] (rpe_a4_proj combat log)') ON DUPLICATE KEY UPDATE `event_type`=VALUES(`event_type`), `event_phase_mask`=VALUES(`event_phase_mask`), `event_chance`=VALUES(`event_chance`), `event_flags`=VALUES(`event_flags`), `event_param1`=VALUES(`event_param1`), `event_param2`=VALUES(`event_param2`), `event_param3`=VALUES(`event_param3`), `event_param4`=VALUES(`event_param4`), `event_param5`=VALUES(`event_param5`), `action_type`=VALUES(`action_type`), `action_param1`=VALUES(`action_param1`), `action_param2`=VALUES(`action_param2`), `action_param3`=VALUES(`action_param3`), `action_param4`=VALUES(`action_param4`), `action_param5`=VALUES(`action_param5`), `action_param6`=VALUES(`action_param6`), `action_param7`=VALUES(`action_param7`), `target_type`=VALUES(`target_type`), `target_param1`=VALUES(`target_param1`), `target_param2`=VALUES(`target_param2`), `target_param3`=VALUES(`target_param3`), `target_param4`=VALUES(`target_param4`), `target_x`=VALUES(`target_x`), `target_y`=VALUES(`target_y`), `target_z`=VALUES(`target_z`), `target_o`=VALUES(`target_o`), `comment`=VALUES(`comment`);
-- [HIGH] combatlog: entry 244675 UNIT_DIED, last observed cast spell 305913
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `action_param7`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (244675, 0, 6, 0, 6, 0, 100, 0, 0, 0, 0, 0, 0, 11, 305913, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Runk - On HP 0-0% - Cast 305913 [HIGH] (rpe_a4_proj combat log)') ON DUPLICATE KEY UPDATE `event_type`=VALUES(`event_type`), `event_phase_mask`=VALUES(`event_phase_mask`), `event_chance`=VALUES(`event_chance`), `event_flags`=VALUES(`event_flags`), `event_param1`=VALUES(`event_param1`), `event_param2`=VALUES(`event_param2`), `event_param3`=VALUES(`event_param3`), `event_param4`=VALUES(`event_param4`), `event_param5`=VALUES(`event_param5`), `action_type`=VALUES(`action_type`), `action_param1`=VALUES(`action_param1`), `action_param2`=VALUES(`action_param2`), `action_param3`=VALUES(`action_param3`), `action_param4`=VALUES(`action_param4`), `action_param5`=VALUES(`action_param5`), `action_param6`=VALUES(`action_param6`), `action_param7`=VALUES(`action_param7`), `target_type`=VALUES(`target_type`), `target_param1`=VALUES(`target_param1`), `target_param2`=VALUES(`target_param2`), `target_param3`=VALUES(`target_param3`), `target_param4`=VALUES(`target_param4`), `target_x`=VALUES(`target_x`), `target_y`=VALUES(`target_y`), `target_z`=VALUES(`target_z`), `target_o`=VALUES(`target_o`), `comment`=VALUES(`comment`);
-- creature 244676 'Kobold Pillager' realm AIName='' ScriptName=''
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=244676 AND `AIName`='' AND `ScriptName`='';
-- [HIGH] combatlog: entry 244676 UNIT_DIED, last observed cast spell 448341
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `action_param7`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (244676, 0, 0, 0, 6, 0, 100, 0, 0, 0, 0, 0, 0, 11, 448341, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Kobold Pillager - On HP 0-0% - Cast 448341 [HIGH] (rpe_a4_proj combat log)') ON DUPLICATE KEY UPDATE `event_type`=VALUES(`event_type`), `event_phase_mask`=VALUES(`event_phase_mask`), `event_chance`=VALUES(`event_chance`), `event_flags`=VALUES(`event_flags`), `event_param1`=VALUES(`event_param1`), `event_param2`=VALUES(`event_param2`), `event_param3`=VALUES(`event_param3`), `event_param4`=VALUES(`event_param4`), `event_param5`=VALUES(`event_param5`), `action_type`=VALUES(`action_type`), `action_param1`=VALUES(`action_param1`), `action_param2`=VALUES(`action_param2`), `action_param3`=VALUES(`action_param3`), `action_param4`=VALUES(`action_param4`), `action_param5`=VALUES(`action_param5`), `action_param6`=VALUES(`action_param6`), `action_param7`=VALUES(`action_param7`), `target_type`=VALUES(`target_type`), `target_param1`=VALUES(`target_param1`), `target_param2`=VALUES(`target_param2`), `target_param3`=VALUES(`target_param3`), `target_param4`=VALUES(`target_param4`), `target_x`=VALUES(`target_x`), `target_y`=VALUES(`target_y`), `target_z`=VALUES(`target_z`), `target_o`=VALUES(`target_o`), `comment`=VALUES(`comment`);
-- creature 244677 'Kobold Firetender' realm AIName='SmartAI' ScriptName=''
-- [HIGH] combatlog: entry 244677 UNIT_DIED, last observed cast spell 448429
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `action_param7`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (244677, 0, 1, 0, 6, 0, 100, 0, 0, 0, 0, 0, 0, 11, 448429, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Kobold Firetender - On HP 0-0% - Cast 448429 [HIGH] (rpe_a4_proj combat log)') ON DUPLICATE KEY UPDATE `event_type`=VALUES(`event_type`), `event_phase_mask`=VALUES(`event_phase_mask`), `event_chance`=VALUES(`event_chance`), `event_flags`=VALUES(`event_flags`), `event_param1`=VALUES(`event_param1`), `event_param2`=VALUES(`event_param2`), `event_param3`=VALUES(`event_param3`), `event_param4`=VALUES(`event_param4`), `event_param5`=VALUES(`event_param5`), `action_type`=VALUES(`action_type`), `action_param1`=VALUES(`action_param1`), `action_param2`=VALUES(`action_param2`), `action_param3`=VALUES(`action_param3`), `action_param4`=VALUES(`action_param4`), `action_param5`=VALUES(`action_param5`), `action_param6`=VALUES(`action_param6`), `action_param7`=VALUES(`action_param7`), `target_type`=VALUES(`target_type`), `target_param1`=VALUES(`target_param1`), `target_param2`=VALUES(`target_param2`), `target_param3`=VALUES(`target_param3`), `target_param4`=VALUES(`target_param4`), `target_x`=VALUES(`target_x`), `target_y`=VALUES(`target_y`), `target_z`=VALUES(`target_z`), `target_o`=VALUES(`target_o`), `comment`=VALUES(`comment`);
-- creature 244682 'Kobold Waxmancer' realm AIName='SmartAI' ScriptName=''
-- [HIGH] combatlog: entry 244682 spell 448429 cast only observed at <= 40% HP (n=2); fires once while HP is in [0,40]% -- NOT_REPEATABLE (v1 does not infer a real repeat cadence f
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `action_param7`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (244682, 0, 1, 0, 2, 0, 100, 1, 0, 40, 0, 0, 0, 11, 448429, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Kobold Waxmancer - On HP 0-40% - Cast 448429 [HIGH] (rpe_a4_proj combat log)') ON DUPLICATE KEY UPDATE `event_type`=VALUES(`event_type`), `event_phase_mask`=VALUES(`event_phase_mask`), `event_chance`=VALUES(`event_chance`), `event_flags`=VALUES(`event_flags`), `event_param1`=VALUES(`event_param1`), `event_param2`=VALUES(`event_param2`), `event_param3`=VALUES(`event_param3`), `event_param4`=VALUES(`event_param4`), `event_param5`=VALUES(`event_param5`), `action_type`=VALUES(`action_type`), `action_param1`=VALUES(`action_param1`), `action_param2`=VALUES(`action_param2`), `action_param3`=VALUES(`action_param3`), `action_param4`=VALUES(`action_param4`), `action_param5`=VALUES(`action_param5`), `action_param6`=VALUES(`action_param6`), `action_param7`=VALUES(`action_param7`), `target_type`=VALUES(`target_type`), `target_param1`=VALUES(`target_param1`), `target_param2`=VALUES(`target_param2`), `target_param3`=VALUES(`target_param3`), `target_param4`=VALUES(`target_param4`), `target_x`=VALUES(`target_x`), `target_y`=VALUES(`target_y`), `target_z`=VALUES(`target_z`), `target_o`=VALUES(`target_o`), `comment`=VALUES(`comment`);
-- [HIGH] combatlog: entry 244682 UNIT_DIED, last observed cast spell 448429
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `action_param7`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (244682, 0, 2, 0, 6, 0, 100, 0, 0, 0, 0, 0, 0, 11, 448429, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Kobold Waxmancer - On HP 0-0% - Cast 448429 [HIGH] (rpe_a4_proj combat log)') ON DUPLICATE KEY UPDATE `event_type`=VALUES(`event_type`), `event_phase_mask`=VALUES(`event_phase_mask`), `event_chance`=VALUES(`event_chance`), `event_flags`=VALUES(`event_flags`), `event_param1`=VALUES(`event_param1`), `event_param2`=VALUES(`event_param2`), `event_param3`=VALUES(`event_param3`), `event_param4`=VALUES(`event_param4`), `event_param5`=VALUES(`event_param5`), `action_type`=VALUES(`action_type`), `action_param1`=VALUES(`action_param1`), `action_param2`=VALUES(`action_param2`), `action_param3`=VALUES(`action_param3`), `action_param4`=VALUES(`action_param4`), `action_param5`=VALUES(`action_param5`), `action_param6`=VALUES(`action_param6`), `action_param7`=VALUES(`action_param7`), `target_type`=VALUES(`target_type`), `target_param1`=VALUES(`target_param1`), `target_param2`=VALUES(`target_param2`), `target_param3`=VALUES(`target_param3`), `target_param4`=VALUES(`target_param4`), `target_x`=VALUES(`target_x`), `target_y`=VALUES(`target_y`), `target_z`=VALUES(`target_z`), `target_o`=VALUES(`target_o`), `comment`=VALUES(`comment`);
-- creature 244683 'Gnoll Prowler' realm AIName='' ScriptName=''
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=244683 AND `AIName`='' AND `ScriptName`='';
-- [HIGH] combatlog: entry 244683 UNIT_DIED, last observed cast spell 372397
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `action_param7`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (244683, 0, 0, 0, 6, 0, 100, 0, 0, 0, 0, 0, 0, 11, 372397, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Gnoll Prowler - On HP 0-0% - Cast 372397 [HIGH] (rpe_a4_proj combat log)') ON DUPLICATE KEY UPDATE `event_type`=VALUES(`event_type`), `event_phase_mask`=VALUES(`event_phase_mask`), `event_chance`=VALUES(`event_chance`), `event_flags`=VALUES(`event_flags`), `event_param1`=VALUES(`event_param1`), `event_param2`=VALUES(`event_param2`), `event_param3`=VALUES(`event_param3`), `event_param4`=VALUES(`event_param4`), `event_param5`=VALUES(`event_param5`), `action_type`=VALUES(`action_type`), `action_param1`=VALUES(`action_param1`), `action_param2`=VALUES(`action_param2`), `action_param3`=VALUES(`action_param3`), `action_param4`=VALUES(`action_param4`), `action_param5`=VALUES(`action_param5`), `action_param6`=VALUES(`action_param6`), `action_param7`=VALUES(`action_param7`), `target_type`=VALUES(`target_type`), `target_param1`=VALUES(`target_param1`), `target_param2`=VALUES(`target_param2`), `target_param3`=VALUES(`target_param3`), `target_param4`=VALUES(`target_param4`), `target_x`=VALUES(`target_x`), `target_y`=VALUES(`target_y`), `target_z`=VALUES(`target_z`), `target_o`=VALUES(`target_o`), `comment`=VALUES(`comment`);
-- creature 244685 'Ogre Basher' realm AIName='SmartAI' ScriptName=''
-- REVIEW (not applied): combatlog: entry 244685 spell 1270770 cast only observed at <= 40% HP (n=1); fires once while HP is in [0,40]% -- NOT_REPEATABLE (v1 does not infer a real repeat cadence 
-- INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `action_param7`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (244685, 0, 2, 0, 2, 0, 100, 1, 0, 40, 0, 0, 0, 11, 1270770, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Ogre Basher - On HP 0-40% - Cast 1270770 [HIGH] (rpe_a4_proj combat log)') ON DUPLICATE KEY UPDATE `event_type`=VALUES(`event_type`), `event_phase_mask`=VALUES(`event_phase_mask`), `event_chance`=VALUES(`event_chance`), `event_flags`=VALUES(`event_flags`), `event_param1`=VALUES(`event_param1`), `event_param2`=VALUES(`event_param2`), `event_param3`=VALUES(`event_param3`), `event_param4`=VALUES(`event_param4`), `event_param5`=VALUES(`event_param5`), `action_type`=VALUES(`action_type`), `action_param1`=VALUES(`action_param1`), `action_param2`=VALUES(`action_param2`), `action_param3`=VALUES(`action_param3`), `action_param4`=VALUES(`action_param4`), `action_param5`=VALUES(`action_param5`), `action_param6`=VALUES(`action_param6`), `action_param7`=VALUES(`action_param7`), `target_type`=VALUES(`target_type`), `target_param1`=VALUES(`target_param1`), `target_param2`=VALUES(`target_param2`), `target_param3`=VALUES(`target_param3`), `target_param4`=VALUES(`target_param4`), `target_x`=VALUES(`target_x`), `target_y`=VALUES(`target_y`), `target_z`=VALUES(`target_z`), `target_o`=VALUES(`target_o`), `comment`=VALUES(`comment`);
-- REVIEW (not applied): combatlog: entry 244685 spell 1270769 cast only observed at <= 20% HP (n=1); fires once while HP is in [0,20]% -- NOT_REPEATABLE (v1 does not infer a real repeat cadence 
-- INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `action_param7`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (244685, 0, 2, 0, 2, 0, 100, 1, 0, 20, 0, 0, 0, 11, 1270769, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Ogre Basher - On HP 0-20% - Cast 1270769 [HIGH] (rpe_a4_proj combat log)') ON DUPLICATE KEY UPDATE `event_type`=VALUES(`event_type`), `event_phase_mask`=VALUES(`event_phase_mask`), `event_chance`=VALUES(`event_chance`), `event_flags`=VALUES(`event_flags`), `event_param1`=VALUES(`event_param1`), `event_param2`=VALUES(`event_param2`), `event_param3`=VALUES(`event_param3`), `event_param4`=VALUES(`event_param4`), `event_param5`=VALUES(`event_param5`), `action_type`=VALUES(`action_type`), `action_param1`=VALUES(`action_param1`), `action_param2`=VALUES(`action_param2`), `action_param3`=VALUES(`action_param3`), `action_param4`=VALUES(`action_param4`), `action_param5`=VALUES(`action_param5`), `action_param6`=VALUES(`action_param6`), `action_param7`=VALUES(`action_param7`), `target_type`=VALUES(`target_type`), `target_param1`=VALUES(`target_param1`), `target_param2`=VALUES(`target_param2`), `target_param3`=VALUES(`target_param3`), `target_param4`=VALUES(`target_param4`), `target_x`=VALUES(`target_x`), `target_y`=VALUES(`target_y`), `target_z`=VALUES(`target_z`), `target_o`=VALUES(`target_o`), `comment`=VALUES(`comment`);
-- [HIGH] combatlog: entry 244685 spell 33239 cast only observed at <= 10% HP (n=6); fires once while HP is in [0,10]% -- NOT_REPEATABLE (v1 does not infer a real repeat cadence fo
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `action_param7`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (244685, 0, 2, 0, 2, 0, 100, 1, 0, 10, 0, 0, 0, 11, 33239, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Ogre Basher - On HP 0-10% - Cast 33239 [HIGH] (rpe_a4_proj combat log)') ON DUPLICATE KEY UPDATE `event_type`=VALUES(`event_type`), `event_phase_mask`=VALUES(`event_phase_mask`), `event_chance`=VALUES(`event_chance`), `event_flags`=VALUES(`event_flags`), `event_param1`=VALUES(`event_param1`), `event_param2`=VALUES(`event_param2`), `event_param3`=VALUES(`event_param3`), `event_param4`=VALUES(`event_param4`), `event_param5`=VALUES(`event_param5`), `action_type`=VALUES(`action_type`), `action_param1`=VALUES(`action_param1`), `action_param2`=VALUES(`action_param2`), `action_param3`=VALUES(`action_param3`), `action_param4`=VALUES(`action_param4`), `action_param5`=VALUES(`action_param5`), `action_param6`=VALUES(`action_param6`), `action_param7`=VALUES(`action_param7`), `target_type`=VALUES(`target_type`), `target_param1`=VALUES(`target_param1`), `target_param2`=VALUES(`target_param2`), `target_param3`=VALUES(`target_param3`), `target_param4`=VALUES(`target_param4`), `target_x`=VALUES(`target_x`), `target_y`=VALUES(`target_y`), `target_z`=VALUES(`target_z`), `target_o`=VALUES(`target_o`), `comment`=VALUES(`comment`);
-- [HIGH] combatlog: entry 244685 UNIT_DIED, last observed cast spell 33239
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `action_param7`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (244685, 0, 3, 0, 6, 0, 100, 0, 0, 0, 0, 0, 0, 11, 33239, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Ogre Basher - On HP 0-0% - Cast 33239 [HIGH] (rpe_a4_proj combat log)') ON DUPLICATE KEY UPDATE `event_type`=VALUES(`event_type`), `event_phase_mask`=VALUES(`event_phase_mask`), `event_chance`=VALUES(`event_chance`), `event_flags`=VALUES(`event_flags`), `event_param1`=VALUES(`event_param1`), `event_param2`=VALUES(`event_param2`), `event_param3`=VALUES(`event_param3`), `event_param4`=VALUES(`event_param4`), `event_param5`=VALUES(`event_param5`), `action_type`=VALUES(`action_type`), `action_param1`=VALUES(`action_param1`), `action_param2`=VALUES(`action_param2`), `action_param3`=VALUES(`action_param3`), `action_param4`=VALUES(`action_param4`), `action_param5`=VALUES(`action_param5`), `action_param6`=VALUES(`action_param6`), `action_param7`=VALUES(`action_param7`), `target_type`=VALUES(`target_type`), `target_param1`=VALUES(`target_param1`), `target_param2`=VALUES(`target_param2`), `target_param3`=VALUES(`target_param3`), `target_param4`=VALUES(`target_param4`), `target_x`=VALUES(`target_x`), `target_y`=VALUES(`target_y`), `target_z`=VALUES(`target_z`), `target_o`=VALUES(`target_o`), `comment`=VALUES(`comment`);
-- creature 244695 'Ettin Crusher' realm AIName='SmartAI' ScriptName=''
-- [HIGH] combatlog: entry 244695 UNIT_DIED, last observed cast spell 399062
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `action_param7`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (244695, 0, 1, 0, 6, 0, 100, 0, 0, 0, 0, 0, 0, 11, 399062, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Ettin Crusher - On HP 0-0% - Cast 399062 [HIGH] (rpe_a4_proj combat log)') ON DUPLICATE KEY UPDATE `event_type`=VALUES(`event_type`), `event_phase_mask`=VALUES(`event_phase_mask`), `event_chance`=VALUES(`event_chance`), `event_flags`=VALUES(`event_flags`), `event_param1`=VALUES(`event_param1`), `event_param2`=VALUES(`event_param2`), `event_param3`=VALUES(`event_param3`), `event_param4`=VALUES(`event_param4`), `event_param5`=VALUES(`event_param5`), `action_type`=VALUES(`action_type`), `action_param1`=VALUES(`action_param1`), `action_param2`=VALUES(`action_param2`), `action_param3`=VALUES(`action_param3`), `action_param4`=VALUES(`action_param4`), `action_param5`=VALUES(`action_param5`), `action_param6`=VALUES(`action_param6`), `action_param7`=VALUES(`action_param7`), `target_type`=VALUES(`target_type`), `target_param1`=VALUES(`target_param1`), `target_param2`=VALUES(`target_param2`), `target_param3`=VALUES(`target_param3`), `target_param4`=VALUES(`target_param4`), `target_x`=VALUES(`target_x`), `target_y`=VALUES(`target_y`), `target_z`=VALUES(`target_z`), `target_o`=VALUES(`target_o`), `comment`=VALUES(`comment`);
-- creature 244709 'Ro'grok' realm AIName='SmartAI' ScriptName=''
-- REVIEW (not applied): combatlog: entry 244709 spell 317547 cast only observed at <= 50% HP (n=1); fires once while HP is in [0,50]% -- NOT_REPEATABLE (v1 does not infer a real repeat cadence f
-- INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `action_param7`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (244709, 0, 4, 0, 2, 0, 100, 1, 0, 50, 0, 0, 0, 11, 317547, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Ro''grok - On HP 0-50% - Cast 317547 [HIGH] (rpe_a4_proj combat log)') ON DUPLICATE KEY UPDATE `event_type`=VALUES(`event_type`), `event_phase_mask`=VALUES(`event_phase_mask`), `event_chance`=VALUES(`event_chance`), `event_flags`=VALUES(`event_flags`), `event_param1`=VALUES(`event_param1`), `event_param2`=VALUES(`event_param2`), `event_param3`=VALUES(`event_param3`), `event_param4`=VALUES(`event_param4`), `event_param5`=VALUES(`event_param5`), `action_type`=VALUES(`action_type`), `action_param1`=VALUES(`action_param1`), `action_param2`=VALUES(`action_param2`), `action_param3`=VALUES(`action_param3`), `action_param4`=VALUES(`action_param4`), `action_param5`=VALUES(`action_param5`), `action_param6`=VALUES(`action_param6`), `action_param7`=VALUES(`action_param7`), `target_type`=VALUES(`target_type`), `target_param1`=VALUES(`target_param1`), `target_param2`=VALUES(`target_param2`), `target_param3`=VALUES(`target_param3`), `target_param4`=VALUES(`target_param4`), `target_x`=VALUES(`target_x`), `target_y`=VALUES(`target_y`), `target_z`=VALUES(`target_z`), `target_o`=VALUES(`target_o`), `comment`=VALUES(`comment`);
-- [HIGH] combatlog: entry 244709 UNIT_DIED, last observed cast spell 317547
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `action_param7`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (244709, 0, 4, 0, 6, 0, 100, 0, 0, 0, 0, 0, 0, 11, 317547, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Ro''grok - On HP 0-0% - Cast 317547 [HIGH] (rpe_a4_proj combat log)') ON DUPLICATE KEY UPDATE `event_type`=VALUES(`event_type`), `event_phase_mask`=VALUES(`event_phase_mask`), `event_chance`=VALUES(`event_chance`), `event_flags`=VALUES(`event_flags`), `event_param1`=VALUES(`event_param1`), `event_param2`=VALUES(`event_param2`), `event_param3`=VALUES(`event_param3`), `event_param4`=VALUES(`event_param4`), `event_param5`=VALUES(`event_param5`), `action_type`=VALUES(`action_type`), `action_param1`=VALUES(`action_param1`), `action_param2`=VALUES(`action_param2`), `action_param3`=VALUES(`action_param3`), `action_param4`=VALUES(`action_param4`), `action_param5`=VALUES(`action_param5`), `action_param6`=VALUES(`action_param6`), `action_param7`=VALUES(`action_param7`), `target_type`=VALUES(`target_type`), `target_param1`=VALUES(`target_param1`), `target_param2`=VALUES(`target_param2`), `target_param3`=VALUES(`target_param3`), `target_param4`=VALUES(`target_param4`), `target_x`=VALUES(`target_x`), `target_y`=VALUES(`target_y`), `target_z`=VALUES(`target_z`), `target_o`=VALUES(`target_o`), `comment`=VALUES(`comment`);
-- creature 249347 '?' realm AIName='' ScriptName=''
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=249347 AND `AIName`='' AND `ScriptName`='';
-- [HIGH] combatlog: entry 249347 first observed cast spell 1248984 at 100% HP -> AGGRO
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `action_param7`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (249347, 0, 0, 0, 4, 0, 100, 0, 0, 0, 0, 0, 0, 11, 1248984, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, '249347 - On aggro - Cast 1248984 [HIGH] (rpe_a4_proj combat log)') ON DUPLICATE KEY UPDATE `event_type`=VALUES(`event_type`), `event_phase_mask`=VALUES(`event_phase_mask`), `event_chance`=VALUES(`event_chance`), `event_flags`=VALUES(`event_flags`), `event_param1`=VALUES(`event_param1`), `event_param2`=VALUES(`event_param2`), `event_param3`=VALUES(`event_param3`), `event_param4`=VALUES(`event_param4`), `event_param5`=VALUES(`event_param5`), `action_type`=VALUES(`action_type`), `action_param1`=VALUES(`action_param1`), `action_param2`=VALUES(`action_param2`), `action_param3`=VALUES(`action_param3`), `action_param4`=VALUES(`action_param4`), `action_param5`=VALUES(`action_param5`), `action_param6`=VALUES(`action_param6`), `action_param7`=VALUES(`action_param7`), `target_type`=VALUES(`target_type`), `target_param1`=VALUES(`target_param1`), `target_param2`=VALUES(`target_param2`), `target_param3`=VALUES(`target_param3`), `target_param4`=VALUES(`target_param4`), `target_x`=VALUES(`target_x`), `target_y`=VALUES(`target_y`), `target_z`=VALUES(`target_z`), `target_o`=VALUES(`target_o`), `comment`=VALUES(`comment`);
-- creature 257072 'Gnoll Biter' realm AIName='' ScriptName=''
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=257072 AND `AIName`='' AND `ScriptName`='';
-- [HIGH] combatlog: entry 257072 UNIT_DIED, last observed cast spell 1270771
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `action_param7`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (257072, 0, 0, 0, 6, 0, 100, 0, 0, 0, 0, 0, 0, 11, 1270771, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Gnoll Biter - On HP 0-0% - Cast 1270771 [HIGH] (rpe_a4_proj combat log)') ON DUPLICATE KEY UPDATE `event_type`=VALUES(`event_type`), `event_phase_mask`=VALUES(`event_phase_mask`), `event_chance`=VALUES(`event_chance`), `event_flags`=VALUES(`event_flags`), `event_param1`=VALUES(`event_param1`), `event_param2`=VALUES(`event_param2`), `event_param3`=VALUES(`event_param3`), `event_param4`=VALUES(`event_param4`), `event_param5`=VALUES(`event_param5`), `action_type`=VALUES(`action_type`), `action_param1`=VALUES(`action_param1`), `action_param2`=VALUES(`action_param2`), `action_param3`=VALUES(`action_param3`), `action_param4`=VALUES(`action_param4`), `action_param5`=VALUES(`action_param5`), `action_param6`=VALUES(`action_param6`), `action_param7`=VALUES(`action_param7`), `target_type`=VALUES(`target_type`), `target_param1`=VALUES(`target_param1`), `target_param2`=VALUES(`target_param2`), `target_param3`=VALUES(`target_param3`), `target_param4`=VALUES(`target_param4`), `target_x`=VALUES(`target_x`), `target_y`=VALUES(`target_y`), `target_z`=VALUES(`target_z`), `target_o`=VALUES(`target_o`), `comment`=VALUES(`comment`);
-- combat rows: 16 live, 3 review
-- creature_template_spell: the repertoire the log proved (informational for the AI, loader-validated)
INSERT INTO `creature_template_spell` (`CreatureID`, `Index`, `Spell`, `VerifiedBuild`) VALUES (244670, 0, 372369, 69587) ON DUPLICATE KEY UPDATE `Spell`=VALUES(`Spell`), `VerifiedBuild`=VALUES(`VerifiedBuild`);
INSERT INTO `creature_template_spell` (`CreatureID`, `Index`, `Spell`, `VerifiedBuild`) VALUES (244672, 0, 1270764, 69587) ON DUPLICATE KEY UPDATE `Spell`=VALUES(`Spell`), `VerifiedBuild`=VALUES(`VerifiedBuild`);
INSERT INTO `creature_template_spell` (`CreatureID`, `Index`, `Spell`, `VerifiedBuild`) VALUES (244674, 0, 316890, 69587) ON DUPLICATE KEY UPDATE `Spell`=VALUES(`Spell`), `VerifiedBuild`=VALUES(`VerifiedBuild`);
INSERT INTO `creature_template_spell` (`CreatureID`, `Index`, `Spell`, `VerifiedBuild`) VALUES (244675, 0, 305913, 69587) ON DUPLICATE KEY UPDATE `Spell`=VALUES(`Spell`), `VerifiedBuild`=VALUES(`VerifiedBuild`);
INSERT INTO `creature_template_spell` (`CreatureID`, `Index`, `Spell`, `VerifiedBuild`) VALUES (244676, 0, 448341, 69587) ON DUPLICATE KEY UPDATE `Spell`=VALUES(`Spell`), `VerifiedBuild`=VALUES(`VerifiedBuild`);
INSERT INTO `creature_template_spell` (`CreatureID`, `Index`, `Spell`, `VerifiedBuild`) VALUES (244677, 0, 448429, 69587) ON DUPLICATE KEY UPDATE `Spell`=VALUES(`Spell`), `VerifiedBuild`=VALUES(`VerifiedBuild`);
INSERT INTO `creature_template_spell` (`CreatureID`, `Index`, `Spell`, `VerifiedBuild`) VALUES (244682, 0, 448429, 69587) ON DUPLICATE KEY UPDATE `Spell`=VALUES(`Spell`), `VerifiedBuild`=VALUES(`VerifiedBuild`);
INSERT INTO `creature_template_spell` (`CreatureID`, `Index`, `Spell`, `VerifiedBuild`) VALUES (244683, 0, 372397, 69587) ON DUPLICATE KEY UPDATE `Spell`=VALUES(`Spell`), `VerifiedBuild`=VALUES(`VerifiedBuild`);
INSERT INTO `creature_template_spell` (`CreatureID`, `Index`, `Spell`, `VerifiedBuild`) VALUES (244685, 0, 1270770, 69587) ON DUPLICATE KEY UPDATE `Spell`=VALUES(`Spell`), `VerifiedBuild`=VALUES(`VerifiedBuild`);
INSERT INTO `creature_template_spell` (`CreatureID`, `Index`, `Spell`, `VerifiedBuild`) VALUES (244685, 1, 1270769, 69587) ON DUPLICATE KEY UPDATE `Spell`=VALUES(`Spell`), `VerifiedBuild`=VALUES(`VerifiedBuild`);
INSERT INTO `creature_template_spell` (`CreatureID`, `Index`, `Spell`, `VerifiedBuild`) VALUES (244685, 2, 33239, 69587) ON DUPLICATE KEY UPDATE `Spell`=VALUES(`Spell`), `VerifiedBuild`=VALUES(`VerifiedBuild`);
INSERT INTO `creature_template_spell` (`CreatureID`, `Index`, `Spell`, `VerifiedBuild`) VALUES (244695, 0, 399062, 69587) ON DUPLICATE KEY UPDATE `Spell`=VALUES(`Spell`), `VerifiedBuild`=VALUES(`VerifiedBuild`);
INSERT INTO `creature_template_spell` (`CreatureID`, `Index`, `Spell`, `VerifiedBuild`) VALUES (244709, 0, 317547, 69587) ON DUPLICATE KEY UPDATE `Spell`=VALUES(`Spell`), `VerifiedBuild`=VALUES(`VerifiedBuild`);
INSERT INTO `creature_template_spell` (`CreatureID`, `Index`, `Spell`, `VerifiedBuild`) VALUES (249347, 0, 1248984, 69587) ON DUPLICATE KEY UPDATE `Spell`=VALUES(`Spell`), `VerifiedBuild`=VALUES(`VerifiedBuild`);
INSERT INTO `creature_template_spell` (`CreatureID`, `Index`, `Spell`, `VerifiedBuild`) VALUES (257072, 0, 1270771, 69587) ON DUPLICATE KEY UPDATE `Spell`=VALUES(`Spell`), `VerifiedBuild`=VALUES(`VerifiedBuild`);

-- ----------------------------------------------------------------------------------------
-- 6. creature_text -- monster SAY/YELL lines the capturer heard (SMSG_CHAT, sender entry resolved)
--   Triggers are unknown except where a death aligns (Qalashi Djaradin's last words). Lines are
--   additive; the emitter keys (CreatureID, GroupID, ID) so re-apply is safe.
-- ----------------------------------------------------------------------------------------
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `BroadcastTextId`) VALUES (244671, 0, 0, 'Burn... all...', 12, 0, 100.0, 0, 0, 0) ON DUPLICATE KEY UPDATE `Text`=VALUES(`Text`), `Type`=VALUES(`Type`);
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `BroadcastTextId`) VALUES (244671, 0, 1, 'Burn... all...', 12, 0, 100.0, 0, 0, 0) ON DUPLICATE KEY UPDATE `Text`=VALUES(`Text`), `Type`=VALUES(`Type`);
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `BroadcastTextId`) VALUES (244671, 0, 2, 'Burn... all...', 12, 0, 100.0, 0, 0, 0) ON DUPLICATE KEY UPDATE `Text`=VALUES(`Text`), `Type`=VALUES(`Type`);
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `BroadcastTextId`) VALUES (244672, 0, 0, 'Arathi... ours...', 12, 0, 100.0, 0, 0, 0) ON DUPLICATE KEY UPDATE `Text`=VALUES(`Text`), `Type`=VALUES(`Type`);
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `BroadcastTextId`) VALUES (244676, 0, 0, 'We take ogre deal! You no stop!', 12, 0, 100.0, 0, 0, 0) ON DUPLICATE KEY UPDATE `Text`=VALUES(`Text`), `Type`=VALUES(`Type`);
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `BroadcastTextId`) VALUES (244676, 0, 1, 'We take ogre deal! You no stop!', 12, 0, 100.0, 0, 0, 0) ON DUPLICATE KEY UPDATE `Text`=VALUES(`Text`), `Type`=VALUES(`Type`);
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `BroadcastTextId`) VALUES (249456, 0, 0, 'Are you here to help fix up this troublesome bot?', 12, 0, 100.0, 0, 0, 0) ON DUPLICATE KEY UPDATE `Text`=VALUES(`Text`), `Type`=VALUES(`Type`);
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `BroadcastTextId`) VALUES (249347, 0, 0, 'PROGRAM INTERRUPTED! ANALYZING SCHEMA...', 12, 0, 100.0, 0, 0, 0) ON DUPLICATE KEY UPDATE `Text`=VALUES(`Text`), `Type`=VALUES(`Type`);
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `BroadcastTextId`) VALUES (249347, 0, 1, 'RESUMING DEBUG PROTOCOLS.', 12, 0, 100.0, 0, 0, 0) ON DUPLICATE KEY UPDATE `Text`=VALUES(`Text`), `Type`=VALUES(`Type`);
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `BroadcastTextId`) VALUES (249347, 0, 2, 'INCORRECT USE CASE!', 12, 0, 100.0, 0, 0, 0) ON DUPLICATE KEY UPDATE `Text`=VALUES(`Text`), `Type`=VALUES(`Type`);
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `BroadcastTextId`) VALUES (249347, 0, 3, 'PROGRAM INTERRUPTED! ANALYZING SCHEMA...', 12, 0, 100.0, 0, 0, 0) ON DUPLICATE KEY UPDATE `Text`=VALUES(`Text`), `Type`=VALUES(`Type`);
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `BroadcastTextId`) VALUES (249347, 0, 4, 'RESUMING DEBUG PROTOCOLS.', 12, 0, 100.0, 0, 0, 0) ON DUPLICATE KEY UPDATE `Text`=VALUES(`Text`), `Type`=VALUES(`Type`);
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `BroadcastTextId`) VALUES (249347, 0, 5, 'PROGRAM INTERRUPTED! ANALYZING SCHEMA...', 12, 0, 100.0, 0, 0, 0) ON DUPLICATE KEY UPDATE `Text`=VALUES(`Text`), `Type`=VALUES(`Type`);
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `BroadcastTextId`) VALUES (249347, 0, 6, 'PROTOCOLS COMPLETE. RETURNING TO BASE STATE.', 12, 0, 100.0, 0, 0, 0) ON DUPLICATE KEY UPDATE `Text`=VALUES(`Text`), `Type`=VALUES(`Type`);

-- ----------------------------------------------------------------------------------------
-- 7. Beats the realm already scripts the way the wire shows them (verified, nothing to apply)
-- ----------------------------------------------------------------------------------------
-- (no zone-specific verification notes recorded for this map yet)
