-- ============================================================================
-- CONTENT SLICE -- Quest 65997 "Chasing Sendrax"  (Dragon Isles / Waking Shores, map 2444)
-- ============================================================================
-- Branch: content   Path: sql/content/DragonIsles/WakingShores/
-- Source capture: dump_12.1.0.69299_2026-08-17_05-09-00.pkt ("The Walking Shores 3")
-- Generated by TCHarvest; compared READ-ONLY against integ_world.
-- Status: SECTION 3 VERIFIED ON DEV REALM (2026-08-18) -- scene 2920 plays in-game on
--   selecting Sendrax's gossip option. SECTIONS 1 AND 2 REMAIN CANDIDATE: still
--   UNREVIEWED and NOT dev-realm tested (no cast wiring exists for S1, and S2's
--   triggers are still unknown -- see the per-section notes).
--
-- This file is the golden-source home for this quest's captured behavioral
-- content. Apply to the LOCAL INTEGRATION TESTSERVER for validation (Phase C/D);
-- any fix goes BACK into THIS file, never only into the integration DB.
-- Idempotent (ON DUPLICATE KEY UPDATE -> re-apply safe).
--
-- DELTA vs live integ_world: the DB ALREADY has quest 65997, its objective,
-- starter (Azkra 190155), ender (Sendrax 187406), scene_template 2920, and ALL
-- in-area spawns at map-2444 coords. The gaps this slice fills:
--   S1 creature_template_spell -- 10 rows / 6 combat creatures (DB had 0)
--   S2 creature_text           -- Azkra +1, Molten Primalist +3 (review-only, LOW)
--   S3 smart_scripts           -- SCENE_PLAY(2920) on Sendrax == THE wiring gap
-- Confidence per row [HIGH]/[MED]/[LOW]; trigger UNCERTAINTY flagged inline.
-- MAP 2444 (2022 is only the UiMapID).
-- ============================================================================

-- SECTION 1 — creature_template_spell  (DB currently has 0 rows for each of these entries)
-- =====================================================================================
-- Native spells only: unique to a single slice creature, cast >=3x, SpellID >=200000, name
-- thematically native, not DNT, not a player-class ability. `Index` starts at 0 (no existing
-- rows). CAVEAT: these creatures are AIName=SmartAI — creature_template_spell alone does NOT
-- drive a SmartAI creature to cast; the real cast wiring is smart_scripts SMART_ACTION_CAST on
-- an aggro/timer event, whose timings/targets this capture does NOT let us reconstruct. These
-- rows record the OBSERVED native repertoire, not a cast guarantee. REVIEW before applying.

-- [HIGH] 188666 Unleashed Lavaburst — Lavastorm cast 750x / 746x (its signature ability)
INSERT INTO `creature_template_spell` (`CreatureID`, `Index`, `Spell`, `VerifiedBuild`) VALUES
 (188666, 0, 376774, 69299),   -- Lavastorm            [HIGH]
 (188666, 1, 376768, 69299),   -- Lavastorm            [HIGH]
 (188666, 2, 396159, 69299)    -- Magma Spit           [MED] (also seen on 186836; shared djaradin/lava ability)
ON DUPLICATE KEY UPDATE `Spell`=VALUES(`Spell`), `VerifiedBuild`=VALUES(`VerifiedBuild`);

-- [HIGH] 191886 Primalist Lava Conduit — spell name literally matches the creature
INSERT INTO `creature_template_spell` (`CreatureID`, `Index`, `Spell`, `VerifiedBuild`) VALUES
 (191886, 0, 373643, 69299)    -- Primal Lava Conduit  [HIGH]
ON DUPLICATE KEY UPDATE `Spell`=VALUES(`Spell`), `VerifiedBuild`=VALUES(`VerifiedBuild`);

-- [HIGH] 195915 Firava the Rekindler (boss)
INSERT INTO `creature_template_spell` (`CreatureID`, `Index`, `Spell`, `VerifiedBuild`) VALUES
 (195915, 0, 396975, 69299),   -- Flaming Pitch        [HIGH]
 (195915, 1, 396856, 69299)    -- Blazing Whirl        [HIGH]
ON DUPLICATE KEY UPDATE `Spell`=VALUES(`Spell`), `VerifiedBuild`=VALUES(`VerifiedBuild`);

-- [HIGH/MED] 195917 Primal Revenant
INSERT INTO `creature_template_spell` (`CreatureID`, `Index`, `Spell`, `VerifiedBuild`) VALUES
 (195917, 0, 387277, 69299),   -- Molten Bash          [HIGH]
 (195917, 1, 387037, 69299)    -- Burning Spin         [MED]
ON DUPLICATE KEY UPDATE `Spell`=VALUES(`Spell`), `VerifiedBuild`=VALUES(`VerifiedBuild`);

-- [MED] 186825 Molten Primalist
INSERT INTO `creature_template_spell` (`CreatureID`, `Index`, `Spell`, `VerifiedBuild`) VALUES
 (186825, 0, 378150, 69299)    -- Inferno Cloak        [MED]
ON DUPLICATE KEY UPDATE `Spell`=VALUES(`Spell`), `VerifiedBuild`=VALUES(`VerifiedBuild`);

-- [MED] 186836 Lava Burster
INSERT INTO `creature_template_spell` (`CreatureID`, `Index`, `Spell`, `VerifiedBuild`) VALUES
 (186836, 0, 396159, 69299)    -- Magma Spit           [MED]
ON DUPLICATE KEY UPDATE `Spell`=VALUES(`Spell`), `VerifiedBuild`=VALUES(`VerifiedBuild`);

-- NOTE (withheld here): 190171 Ruby Egg Guardian, 188372 Primal Tarasek, 190080 Tarasek
-- Elementalist observed casts were entirely contamination / DNT / SpellID<200000 — no native
-- spell survived the filter, so nothing is emitted for them (honest "none attributable").


-- =====================================================================================
-- SECTION 2 — creature_text  (review-only observed lines)
-- =====================================================================================

-- 190155 Caretaker Azkra — NEW captured line (DB already has a different GroupID 0 line).
--   [LOW] Emitted as review-only. Fired @tick 615036 (~10k BEFORE quest accept) — trigger
--   UNCERTAIN (gossip-hello greeting or proximity OOC). Placed at GroupID 1 to avoid clobbering
--   the existing GroupID 0. **SAI TALK wiring is WITHHELD**: Azkra runs C++ ScriptName
--   'npc_caretaker_azkra190155', which owns her talk — a SAI TALK could double-fire or be dead.
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `BroadcastTextId`, `comment`) VALUES
 (190155, 1, 0, 'Are you looking for the young cadet, Sendrax? She hasn''t returned yet.', 12, 0, 100.0, 0, 0, 0, 'Caretaker Azkra [CANDIDATE LOW; trigger UNCERTAIN; C++-owned NPC, SAI TALK withheld]')  -- [LOW]
ON DUPLICATE KEY UPDATE `Text`=VALUES(`Text`), `Type`=VALUES(`Type`), `Language`=VALUES(`Language`), `Probability`=VALUES(`Probability`), `Emote`=VALUES(`Emote`), `Duration`=VALUES(`Duration`), `BroadcastTextId`=VALUES(`BroadcastTextId`), `comment`=VALUES(`comment`);

-- 186825 Molten Primalist — 3 captured combat lines (DB has 0). [LOW]
--   UNCERTAINTY: these fired @817376 / 838556 / 845713 — AFTER quest 65997 turn-in (764166),
--   during a later Primalist fight. They are combat chatter; grouped as one random SAY group.
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `BroadcastTextId`, `comment`) VALUES
 (186825, 0, 0, 'We will... retake... Azeroth...', 12, 0, 33.0, 0, 0, 0, 'Molten Primalist [CANDIDATE LOW; combat yell; fired post-turn-in @817376]'),
 (186825, 0, 1, 'As it was before, so it will be again!', 12, 0, 33.0, 0, 0, 0, 'Molten Primalist [CANDIDATE LOW; combat yell; @838556]'),
 (186825, 0, 2, 'The Titans ... lied...', 12, 0, 34.0, 0, 0, 0, 'Molten Primalist [CANDIDATE LOW; combat yell; @845713]')
ON DUPLICATE KEY UPDATE `Text`=VALUES(`Text`), `Type`=VALUES(`Type`), `Language`=VALUES(`Language`), `Probability`=VALUES(`Probability`), `Emote`=VALUES(`Emote`), `Duration`=VALUES(`Duration`), `BroadcastTextId`=VALUES(`BroadcastTextId`), `comment`=VALUES(`comment`);

-- OPTIONAL SAI to fire the Molten Primalist lines — WITHHELD as active SQL (trigger not
-- derivable). If a reviewer wants them audible, the defensible guess is SMART_EVENT_AGGRO(4)
-- -> SMART_ACTION_TALK(1, groupID 0). Left commented; DO NOT uncomment without deciding trigger:
-- INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`target_type`,`comment`) VALUES
--  (186825,0,0,0,4,0,100,0,0,0,0,0, 1,0,0, 1, 'Molten Primalist - on aggro - Talk group 0 [CANDIDATE, trigger UNCERTAIN]');


-- =====================================================================================
-- SECTION 3 — smart_scripts : the SCENE-2920 beat on Sendrax (THE ONE WIRING GAP)
-- =====================================================================================
-- Captured: SMSG_PLAY_SCENE (opcode 0x4500DF) sceneId=2920, scriptPackageId=3657, @tick 658902,
--   at (4044.96, 254.76, 54.18, o 5.83) == Sendrax's spawn. scene_template 2920 already exists.
--   No smart_scripts row plays it (action_type=129 exists 5x in DB, never with param1=2920).
--
-- Sendrax's EXISTING SAI (source_type=0): id=0 event=64(GOSSIP_HELLO) action=33
--   (CALL_KILLEDMONSTER) param1=187406 target_type=7 -> gives the "Sendrax found" credit.
-- This chains a NEW row id=1 (does not touch id=0).
--
-- TRIGGER = RESOLVED AND CONFIRMED IN-GAME (2026-08-18): the scene plays. The first
-- candidate used GOSSIP_HELLO + target
-- SELF and NO cutscene played -- two bugs: (1) the capture timeline shows the scene fired
-- ~4300 ticks AFTER the gossip opened, i.e. on SELECTING the option, not on window-open ->
-- correct event is SMART_EVENT_GOSSIP_SELECT(62); (2) SMART_ACTION_SCENE_PLAY plays for a
-- PLAYER, so the target must be the invoking player SMART_TARGET_ACTION_INVOKER(7), not SELF
-- (Sendrax is not a player -> PlayScene never fired).
-- The option is Sendrax's gossip menu 28097, OptionID 2 ("(Quest) What is happening here?",
-- GossipOptionID 55225). GOSSIP_SELECT params = (menuID=28097, actionID=OptionID=2) -- verified
-- empirically against existing GOSSIP_SELECT rows (actionID = the small per-menu OptionID,
-- NOT the GossipOptionID). SMART_ACTION_SCENE_PLAY=129, action_param1=sceneId=2920 (scene_template
-- 2920 exists; PlayScene(2920)). target_type 7 = SMART_TARGET_ACTION_INVOKER.

INSERT INTO `smart_scripts`
 (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,
  `event_param1`,`event_param2`,`event_param3`,`event_param4`,
  `action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,
  `target_type`,`target_param1`,`target_param2`,`target_param3`,`target_param4`,`comment`) VALUES
 (187406, 0, 1, 0, 62, 0, 100, 0,
  28097, 2, 0, 0,
  129, 2920, 0, 0, 0, 0, 0,
  7, 0, 0, 0, 0,
  'Sendrax - on gossip menu 28097 option 2 selected - Play Scene 2920 (quest 65997 Chasing Sendrax) [corrected after in-game no-play 2026-08-18: was GOSSIP_HELLO+SELF; VERIFIED playing 2026-08-18]')
ON DUPLICATE KEY UPDATE `event_type`=VALUES(`event_type`), `event_param1`=VALUES(`event_param1`), `event_param2`=VALUES(`event_param2`), `action_type`=VALUES(`action_type`), `action_param1`=VALUES(`action_param1`), `target_type`=VALUES(`target_type`), `comment`=VALUES(`comment`);

-- =====================================================================================
-- END -- review each row's confidence + uncertainty flag before applying to a feature branch.
--
-- APPLY NOTE (learned the hard way 2026-08-18): `.reload smart_scripts` is NOT enough to
-- test a smart_scripts change against an already-spawned creature. SmartScript::OnInitialize
-- takes a COPY of the event list (SmartScript.cpp: "load copy of script"), taken once at
-- AddToWorld() -> AIM_Initialize(). HandleReloadSmartScripts only refreshes the manager and
-- never re-initializes anything already in the world, so the live NPC keeps running the old
-- script and the change looks like it did nothing. Target the NPC and `.die` then `.respawn`
-- (`.respawn` on a selected target only acts if it is dead), or restart the realm.
-- =====================================================================================
